package provider

import (
	"context"
	"fmt"
	"slices"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netcheck-de/terraform-provider-redshift/internal/sqlclient"
)

// tableResource manages the definition of one local Redshift table, never its rows.
type tableResource struct {
	// resourceClient provides SQL execution and warehouse ownership checks.
	resourceClient
}

// tableModel is the Terraform state of a table definition.
type tableModel struct {
	// ID records the warehouse/database/schema/table identity.
	ID types.String `tfsdk:"id"`
	// Database contains the table.
	Database types.String `tfsdk:"database"`
	// Schema contains the table.
	Schema types.String `tfsdk:"schema"`
	// Name identifies the table.
	Name types.String `tfsdk:"name"`
	// Owner is the owning user, managed when configured.
	Owner types.String `tfsdk:"owner"`
	// Columns are the ordered column definitions.
	Columns types.List `tfsdk:"columns"`
	// PrimaryKey lists the primary key columns.
	PrimaryKey types.List `tfsdk:"primary_key"`
	// Unique holds the column lists of UNIQUE constraints.
	Unique types.Set `tfsdk:"unique"`
	// ForeignKeys holds the FOREIGN KEY constraints.
	ForeignKeys types.Set `tfsdk:"foreign_keys"`
	// DistStyle is AUTO, EVEN, KEY, or ALL.
	DistStyle types.String `tfsdk:"diststyle"`
	// DistKey is the DISTSTYLE KEY column.
	DistKey types.String `tfsdk:"distkey"`
	// SortKeyStyle is AUTO, COMPOUND, or INTERLEAVED.
	SortKeyStyle types.String `tfsdk:"sortkey_style"`
	// SortKey lists the sort key columns.
	SortKey types.List `tfsdk:"sortkey"`
	// Backup is YES or NO.
	Backup types.String `tfsdk:"backup"`
}

// tableColumnModel is one element of columns.
type tableColumnModel struct {
	// Name is the column name.
	Name types.String `tfsdk:"name"`
	// Type is the configured data type.
	Type types.String `tfsdk:"type"`
	// Encoding is the compression encoding.
	Encoding types.String `tfsdk:"encoding"`
	// Nullable reports whether NULL is allowed.
	Nullable types.Bool `tfsdk:"nullable"`
	// Default is the DEFAULT expression.
	Default types.String `tfsdk:"default"`
	// Identity holds the identity clause.
	Identity types.Object `tfsdk:"identity"`
}

// tableIdentityModel is the identity clause of a column.
type tableIdentityModel struct {
	// Seed is the first generated value.
	Seed types.Int64 `tfsdk:"seed"`
	// Step is the increment.
	Step types.Int64 `tfsdk:"step"`
	// GeneratedByDefault selects GENERATED BY DEFAULT AS IDENTITY.
	GeneratedByDefault types.Bool `tfsdk:"generated_by_default"`
}

// tableForeignKeyModel is one element of foreign_keys.
type tableForeignKeyModel struct {
	// Columns are the referencing columns.
	Columns types.List `tfsdk:"columns"`
	// ReferencesSchema contains the referenced table.
	ReferencesSchema types.String `tfsdk:"references_schema"`
	// ReferencesTable is the referenced table.
	ReferencesTable types.String `tfsdk:"references_table"`
	// ReferencesColumns are the referenced columns.
	ReferencesColumns types.List `tfsdk:"references_columns"`
}

// Attribute types of the nested values, for building them outside the schema.
var (
	tableIdentityAttributeTypes = map[string]attr.Type{"seed": types.Int64Type, "step": types.Int64Type, "generated_by_default": types.BoolType}
	tableColumnAttributeTypes   = map[string]attr.Type{
		"name": types.StringType, "type": types.StringType, "encoding": types.StringType, "nullable": types.BoolType,
		"default": types.StringType, "identity": types.ObjectType{AttrTypes: tableIdentityAttributeTypes},
	}
	tableForeignKeyAttributeTypes = map[string]attr.Type{
		"columns": types.ListType{ElemType: types.StringType}, "references_schema": types.StringType,
		"references_table": types.StringType, "references_columns": types.ListType{ElemType: types.StringType},
	}
)

// tableNullModel returns a model whose optional values are typed nulls, for lookups and import.
func tableNullModel(database, schemaName, name types.String) tableModel {
	return tableModel{
		ID: types.StringNull(), Database: database, Schema: schemaName, Name: name, Owner: types.StringNull(),
		Columns:     types.ListNull(types.ObjectType{AttrTypes: tableColumnAttributeTypes}),
		PrimaryKey:  types.ListNull(types.StringType),
		Unique:      types.SetNull(types.ListType{ElemType: types.StringType}),
		ForeignKeys: types.SetNull(types.ObjectType{AttrTypes: tableForeignKeyAttributeTypes}),
		DistStyle:   types.StringNull(), DistKey: types.StringNull(), SortKeyStyle: types.StringNull(),
		SortKey: types.ListNull(types.StringType), Backup: types.StringNull(),
	}
}

var _ = registerResource(newTableResource)

// newTableResource constructs a table definition handler.
func newTableResource() resource.Resource { return &tableResource{} }

// Metadata identifies the table resource to Terraform.
func (r *tableResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_table"
}

// tableReplacementDescription documents the conditional replacement of an attribute in plans.
const tableReplacementDescription = "Replaces the table when ALTER TABLE cannot make the change in place."

// Schema defines the table identity, columns, constraints, and physical layout.
func (r *tableResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	replaceList := func(attribute string) planmodifier.List {
		return listplanmodifier.RequiresReplaceIf(func(ctx context.Context, req planmodifier.ListRequest, resp *listplanmodifier.RequiresReplaceIfFuncResponse) {
			resp.RequiresReplace = tableRequiresReplace(ctx, req.State, req.Plan, attribute)
		}, tableReplacementDescription, tableReplacementDescription)
	}
	replaceString := func(attribute string) planmodifier.String {
		return stringplanmodifier.RequiresReplaceIf(func(ctx context.Context, req planmodifier.StringRequest, resp *stringplanmodifier.RequiresReplaceIfFuncResponse) {
			resp.RequiresReplace = tableRequiresReplace(ctx, req.State, req.Plan, attribute)
		}, tableReplacementDescription, tableReplacementDescription)
	}
	names := func(description string) schema.ListAttribute {
		return schema.ListAttribute{Required: true, ElementType: types.StringType, MarkdownDescription: description, Validators: []validator.List{listvalidator.SizeAtLeast(1)}}
	}
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages the definition of a local Redshift table: columns, constraints, distribution, sort key, and owner. Rows are never managed; changes that ALTER TABLE cannot make replace the table, which drops its data.",
		Attributes: map[string]schema.Attribute{
			"id": idAttribute(),
			"database": schema.StringAttribute{
				Required: true, MarkdownDescription: "Local database containing the table. Changing it replaces the table.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"schema": schema.StringAttribute{
				Required: true, MarkdownDescription: "Existing schema containing the table, in lowercase. Changing it replaces the table.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true, MarkdownDescription: "Table name, in lowercase, because Redshift folds ASCII letters of identifiers to lowercase. Changing it replaces the table.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"owner": schema.StringAttribute{
				Optional: true, Computed: true,
				MarkdownDescription: "User owning the table, in lowercase. Set it to transfer ownership with `ALTER TABLE ... OWNER TO`; omit it to keep the creating user.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"columns": schema.ListNestedAttribute{
				Required: true,
				MarkdownDescription: "Ordered column definitions (1 to 1600). In place, columns can be appended with `ALTER TABLE ADD COLUMN` (not identity columns, and NOT NULL columns only with a default), " +
					"removed with `DROP COLUMN`, re-encoded with `ALTER COLUMN ... ENCODE` (not with an interleaved sort key), and VARCHAR or VARBYTE columns without a default, " +
					"constraint, or `BYTEDICT`/`RUNLENGTH`/`TEXT255`/`TEXT32K` encoding can be widened with `ALTER COLUMN ... TYPE`. Any other change, including " +
					"reordering, renaming, or changing a type, nullability, default, or identity, replaces the table.",
				Validators:    []validator.List{listvalidator.SizeBetween(1, tableMaxColumns)},
				PlanModifiers: []planmodifier.List{tableColumnDefaults{}, replaceList("columns")},
				NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{Required: true, MarkdownDescription: "Column name, in lowercase.", Validators: []validator.String{stringvalidator.LengthAtLeast(1)}},
					"type": schema.StringAttribute{
						Required:            true,
						MarkdownDescription: "Redshift data type, such as `bigint`, `numeric(12,2)`, or `varchar(256)`. Aliases are compared by their canonical form, and a type without a length gets the one Redshift applies, for example `varchar` is `character varying(256)`.",
					},
					"encoding": schema.StringAttribute{
						Optional: true, Computed: true,
						MarkdownDescription: "Compression encoding: `AZ64`, `BYTEDICT`, `DELTA`, `DELTA32K`, `LZO`, `MOSTLY8`, `MOSTLY16`, `MOSTLY32`, `RAW`, `RUNLENGTH`, `TEXT255`, `TEXT32K`, or `ZSTD`. Omit it to let Redshift choose; the chosen encoding is reported. A sort key change can re-encode columns of the old and new key, for example to `RAW`: their omitted encodings are then known after apply, and configured ones are applied again.",
						Validators:          []validator.String{stringvalidator.OneOf(tableKeywordStrings(tableEncodings)...)},
					},
					"nullable": schema.BoolAttribute{
						Optional: true, Computed: true,
						MarkdownDescription: "Whether the column accepts NULL. Omitted, it is `false` for identity and primary key columns, and otherwise `true` for a new column while an existing column keeps its nullability.",
					},
					"default": schema.StringAttribute{
						Optional:            true,
						MarkdownDescription: "DEFAULT expression embedded as SQL, so string literals need quotes, for example `'n/a'` or `getdate()`. Redshift stores it with casts and its own spacing; the configured text is kept while the column has a default, and a change replaces the table.",
						Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
					},
					"identity": schema.SingleNestedAttribute{
						Optional:            true,
						MarkdownDescription: "Makes an INTEGER or BIGINT column an `IDENTITY(seed, step)` column, which is always NOT NULL.",
						Attributes: map[string]schema.Attribute{
							"seed": schema.Int64Attribute{Required: true, MarkdownDescription: "First generated value."},
							"step": schema.Int64Attribute{Required: true, MarkdownDescription: "Increment between generated values; must not be zero."},
							"generated_by_default": schema.BoolAttribute{
								Optional: true, Computed: true, Default: booldefault.StaticBool(false),
								MarkdownDescription: "Use `GENERATED BY DEFAULT AS IDENTITY`, which lets inserts supply their own values; defaults to `false`.",
							},
						},
					},
				}},
			},
			"primary_key": schema.ListAttribute{
				Optional: true, ElementType: types.StringType,
				MarkdownDescription: "Ordered primary key columns. Redshift does not enforce it but uses it for planning. It is added and dropped with `ALTER TABLE ADD PRIMARY KEY` and `DROP CONSTRAINT`; a new primary key on an existing nullable column, or on a new column without a default, replaces the table.",
				PlanModifiers:       []planmodifier.List{replaceList("primary_key")},
			},
			"unique": schema.SetAttribute{
				Optional: true, ElementType: types.ListType{ElemType: types.StringType},
				MarkdownDescription: "UNIQUE constraints, each an ordered list of columns. Redshift does not enforce them. Changes are applied with `ALTER TABLE ADD UNIQUE` and `DROP CONSTRAINT`.",
			},
			"foreign_keys": schema.SetNestedAttribute{
				Optional:            true,
				MarkdownDescription: "FOREIGN KEY constraints. Redshift does not enforce them. Changes are applied with `ALTER TABLE ADD FOREIGN KEY` and `DROP CONSTRAINT`.",
				NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
					"columns":            names("Referencing columns of this table."),
					"references_schema":  schema.StringAttribute{Required: true, MarkdownDescription: "Schema of the referenced table."},
					"references_table":   schema.StringAttribute{Required: true, MarkdownDescription: "Referenced table."},
					"references_columns": names("Referenced columns, matched to `columns` by position; they must form a primary key or unique constraint of the referenced table."),
				}},
			},
			"diststyle": schema.StringAttribute{
				Optional: true, Computed: true,
				MarkdownDescription: "Distribution style: `AUTO`, `EVEN`, `KEY`, or `ALL`. Omitted, it is `KEY` when `distkey` is set and `AUTO` otherwise. `AUTO` covers whatever `AUTO(ALL)`, `AUTO(EVEN)`, or `AUTO(KEY(column))` Redshift currently applies. Changes use `ALTER TABLE ALTER DISTSTYLE`; with an interleaved sort key they replace the table. A move to `AUTO` that drops the key column distributes `EVEN` until the column is dropped.",
				Validators:          []validator.String{stringvalidator.OneOf(tableKeywordStrings(tableDistStyles)...)},
				PlanModifiers:       []planmodifier.String{tableDerivedStyle{source: "distkey"}, replaceString("diststyle")},
			},
			"distkey": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Distribution key column for `diststyle = \"KEY\"`, of type BOOLEAN, REAL, DOUBLE PRECISION, SMALLINT, INTEGER, BIGINT, DECIMAL, DATE, TIME, TIMETZ, TIMESTAMP, TIMESTAMPTZ, CHAR, or VARCHAR. Changes use `ALTER TABLE ALTER DISTKEY`; with an interleaved sort key they replace the table.",
				PlanModifiers:       []planmodifier.String{replaceString("distkey")},
			},
			"sortkey_style": schema.StringAttribute{
				Optional: true, Computed: true,
				MarkdownDescription: "Sort key style: `AUTO`, `COMPOUND`, or `INTERLEAVED`. Omitted, it is `COMPOUND` when `sortkey` is set and `AUTO` otherwise. Changes to `AUTO` or a compound key use `ALTER TABLE ALTER SORTKEY`; a move to `AUTO` from an interleaved key or off a dropped column first runs `ALTER SORTKEY NONE`. Creating or changing an interleaved sort key replaces the table. A table without sort key columns is reported as `AUTO`.",
				Validators:          []validator.String{stringvalidator.OneOf(tableKeywordStrings(tableSortKeyStyles)...)},
				PlanModifiers:       []planmodifier.String{tableDerivedStyle{source: "sortkey"}, replaceString("sortkey_style")},
			},
			"sortkey": schema.ListAttribute{
				Optional: true, ElementType: types.StringType,
				MarkdownDescription: "Ordered sort key columns, at most 400 for a compound and 8 for an interleaved key, of the types `distkey` allows; omit for `AUTO`.",
				PlanModifiers:       []planmodifier.List{replaceList("sortkey")},
			},
			"backup": schema.StringAttribute{
				Optional: true, Computed: true, Default: stringdefault.StaticString("YES"),
				MarkdownDescription: "`YES` or `NO` (defaults to `YES`): whether snapshots include the table. RA3 and Serverless always back up tables. Redshift has no ALTER form, so a change replaces the table, except after import, when the value is only recorded; the setting is not read back from the catalog.",
				Validators:          []validator.String{stringvalidator.OneOf(tableKeywordStrings(tableBackupModes)...)},
				PlanModifiers:       []planmodifier.String{replaceString("backup")},
			},
		},
	}
}

// tableKeywordStrings converts an allowlist for schema validators.
func tableKeywordStrings(keywords []sqlclient.Keyword) []string {
	values := make([]string, len(keywords))
	for i, keyword := range keywords {
		values[i] = string(keyword)
	}
	return values
}

// tableRequiresReplace decides whether attribute's change needs a new table. Undecodable values replace, so a
// change is never applied in place without the checks that make ALTER TABLE succeed.
func tableRequiresReplace(ctx context.Context, state tfsdk.State, plan tfsdk.Plan, attribute string) bool {
	var prior, planned tableModel
	if state.Get(ctx, &prior).HasError() || plan.Get(ctx, &planned).HasError() {
		return true
	}
	prevSpec, err := tableSpecOf(prior)
	if err != nil {
		return true
	}
	planSpec, err := tableSpecOf(planned)
	if err != nil {
		return true
	}
	return tableReplacements(prevSpec, planSpec)[attribute] != ""
}

// tableDerivedStyle fills an omitted diststyle or sortkey_style from its key attribute, as Redshift would, so the
// plan shows the style and a drifted style is reset.
type tableDerivedStyle struct {
	// source is distkey or sortkey.
	source string
}

// Description explains the derived default.
func (m tableDerivedStyle) Description(context.Context) string {
	return "Defaults to the style implied by " + m.source + "."
}

// MarkdownDescription explains the derived default.
func (m tableDerivedStyle) MarkdownDescription(ctx context.Context) string { return m.Description(ctx) }

// PlanModifyString derives the style when it is not configured. Configuration it cannot read, as in schema
// tests, leaves the plan alone.
func (m tableDerivedStyle) PlanModifyString(ctx context.Context, req planmodifier.StringRequest, resp *planmodifier.StringResponse) {
	if !req.ConfigValue.IsNull() {
		return
	}
	if m.source == "distkey" {
		var key types.String
		if req.Config.GetAttribute(ctx, path.Root(m.source), &key).HasError() {
			return
		}
		switch {
		case key.IsUnknown():
			resp.PlanValue = types.StringUnknown()
		case key.IsNull():
			resp.PlanValue = types.StringValue("AUTO")
		default:
			resp.PlanValue = types.StringValue("KEY")
		}
		return
	}
	var key types.List
	if req.Config.GetAttribute(ctx, path.Root(m.source), &key).HasError() {
		return
	}
	switch {
	case key.IsUnknown():
		resp.PlanValue = types.StringUnknown()
	case key.IsNull() || len(key.Elements()) == 0:
		resp.PlanValue = types.StringValue("AUTO")
	default:
		resp.PlanValue = types.StringValue("COMPOUND")
	}
}

// tableColumnDefaults fills omitted computed column values: identity and primary key columns are NOT NULL, as
// Redshift makes them, and other columns keep their encoding and nullability or, when new, accept NULL.
type tableColumnDefaults struct{}

// Description explains the column defaults.
func (tableColumnDefaults) Description(context.Context) string {
	return "Existing columns keep their encoding and nullability; new identity and primary key columns are NOT NULL."
}

// MarkdownDescription explains the column defaults.
func (m tableColumnDefaults) MarkdownDescription(ctx context.Context) string {
	return m.Description(ctx)
}

// PlanModifyList fills unknown encoding and nullable values that configuration leaves out.
func (tableColumnDefaults) PlanModifyList(ctx context.Context, req planmodifier.ListRequest, resp *planmodifier.ListResponse) {
	if req.PlanValue.IsNull() || req.PlanValue.IsUnknown() || req.ConfigValue.IsUnknown() {
		return
	}
	var planned, configured, existing []tableColumnModel
	if req.PlanValue.ElementsAs(ctx, &planned, false).HasError() || req.ConfigValue.ElementsAs(ctx, &configured, false).HasError() || len(planned) != len(configured) {
		return
	}
	prior := map[string]tableColumnModel{}
	if !req.StateValue.IsNull() && !req.StateValue.IsUnknown() && !req.StateValue.ElementsAs(ctx, &existing, false).HasError() {
		for _, column := range existing {
			prior[column.Name.ValueString()] = column
		}
	}
	var primaryKey types.List
	keyed := !req.Config.GetAttribute(ctx, path.Root("primary_key"), &primaryKey).HasError() && !primaryKey.IsUnknown()
	keys := map[string]bool{}
	if keyed {
		for _, element := range primaryKey.Elements() {
			if name, ok := element.(types.String); ok {
				keys[name.ValueString()] = true
			}
		}
	}
	moved, allMoved := tableSortKeyMoves(ctx, req.Config, req.State)
	for i := range planned {
		name := planned[i].Name.ValueString()
		before, existed := prior[name]
		if configured[i].Encoding.IsNull() && existed && !before.Encoding.IsUnknown() && !allMoved && !moved[name] {
			planned[i].Encoding = before.Encoding
		}
		if !configured[i].Nullable.IsNull() {
			continue
		}
		switch {
		case !configured[i].Identity.IsNull() || keys[planned[i].Name.ValueString()]:
			planned[i].Nullable = types.BoolValue(false)
		case existed && !before.Nullable.IsUnknown() && !before.Nullable.IsNull():
			planned[i].Nullable = before.Nullable
		case keyed && !configured[i].Identity.IsUnknown():
			planned[i].Nullable = types.BoolValue(true)
		}
	}
	list, diagnostics := types.ListValueFrom(ctx, req.PlanValue.ElementType(ctx), planned)
	if diagnostics.HasError() {
		return
	}
	resp.PlanValue = list
}

// tableSortKeyMoves returns the columns of the prior and configured sort key when the sort key changes, because
// ALTER SORTKEY may re-encode them: "When you alter a sort key, the compression encoding of columns in the new or
// original sort key can change." all is true when the changed key's columns are not all known, as for an unknown
// configuration or a key Redshift chose under AUTO. https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html
func tableSortKeyMoves(ctx context.Context, config tfsdk.Config, state tfsdk.State) (map[string]bool, bool) {
	if state.Raw.IsNull() {
		return nil, false
	}
	var configStyle, stateStyle types.String
	var configKey, stateKey types.List
	if config.GetAttribute(ctx, path.Root("sortkey_style"), &configStyle).HasError() || config.GetAttribute(ctx, path.Root("sortkey"), &configKey).HasError() ||
		state.GetAttribute(ctx, path.Root("sortkey_style"), &stateStyle).HasError() || state.GetAttribute(ctx, path.Root("sortkey"), &stateKey).HasError() {
		return nil, false
	}
	if configStyle.IsUnknown() || configKey.IsUnknown() {
		return nil, true
	}
	style := func(configured types.String, key types.List) string {
		switch {
		case !configured.IsNull() && !configured.IsUnknown():
			return configured.ValueString()
		case len(key.Elements()) > 0:
			return "COMPOUND"
		}
		return "AUTO"
	}
	from, to := style(stateStyle, stateKey), style(configStyle, configKey)
	fromNames, fromErr := tableStringList(stateKey, "sortkey")
	toNames, toErr := tableStringList(configKey, "sortkey")
	switch {
	case fromErr != nil || toErr != nil:
		return nil, true
	case from == to && slices.Equal(fromNames, toNames):
		return nil, false
	}
	columns := map[string]bool{}
	for _, name := range append(fromNames, toNames...) {
		columns[name] = true
	}
	return columns, from == "AUTO"
}

// read refreshes the table under the configured binding. It reports false when the table, its schema, or its
// database is gone, and returns the constraint names an update needs to drop constraints.
func (r *tableResource) read(ctx context.Context, data *tableModel) (bool, map[string]string, error) {
	database := data.Database.ValueString()
	if err := r.bound(data.ID, database); err != nil {
		return false, nil, err
	}
	if exists, err := r.localDatabaseExists(ctx, database); err != nil || !exists {
		return false, nil, err
	}
	spec := tableSpec{schema: data.Schema.ValueString(), name: data.Name.ValueString()}
	tables, err := r.selectRows(ctx, database, readTableQuery(spec))
	if err != nil || len(tables) == 0 {
		return false, nil, err
	}
	if len(tables) != 1 {
		return false, nil, fmt.Errorf("table %q.%q has ambiguous catalog metadata", spec.schema, spec.name)
	}
	attributes, err := r.selectRows(ctx, database, readTableAttributesQuery(spec))
	if err != nil {
		return false, nil, err
	}
	columns, err := r.selectRows(ctx, database, readTableColumnsQuery(database, spec))
	if err != nil {
		return false, nil, err
	}
	constraints, err := r.selectRows(ctx, database, readTableConstraintsQuery(spec))
	if err != nil {
		return false, nil, err
	}
	catalog, err := tableCatalogFrom(tables[0], attributes, columns, constraints)
	if err != nil {
		return false, nil, fmt.Errorf("table %q.%q: %w", spec.schema, spec.name, err)
	}
	if knownString(data.SortKeyStyle) == "AUTO" && tableCatalogCompoundSortKey(catalog) {
		rows, err := r.selectRows(ctx, database, readTableSortKeyQuery(spec))
		if err != nil {
			return false, nil, err
		}
		// ALTER SORTKEY AUTO keeps the current key, and SVV_TABLE_INFO lists only tables with rows, so only an
		// explicit sortkey1 proves that the key is no longer automatic.
		catalog.autoSortKey = len(rows) == 0 || strings.HasPrefix(strings.ToUpper(strings.TrimSpace(rows[0]["sortkey1"])), "AUTO(")
	}
	observed, names, err := tableReconcile(*data, catalog)
	if err != nil {
		return false, nil, fmt.Errorf("table %q.%q: %w", spec.schema, spec.name, err)
	}
	*data = observed
	return true, names, nil
}

// tableCatalogCompoundSortKey reports sort key columns without interleaving, which SORTKEY AUTO can also produce.
func tableCatalogCompoundSortKey(catalog tableCatalog) bool {
	return slices.ContainsFunc(catalog.columns, func(c tableCatalogColumn) bool { return c.sortKey > 0 }) &&
		!slices.ContainsFunc(catalog.columns, func(c tableCatalogColumn) bool { return c.sortKey < 0 })
}

// tableKnownState replaces unknown computed values with nulls, so state written before verification is complete
// and serializable.
func tableKnownState(data tableModel) tableModel {
	for _, value := range []*types.String{&data.Owner, &data.DistStyle, &data.SortKeyStyle, &data.Backup} {
		if value.IsUnknown() {
			*value = types.StringNull()
		}
	}
	var columns []tableColumnModel
	if data.Columns.ElementsAs(context.Background(), &columns, false).HasError() {
		return data
	}
	for i := range columns {
		if columns[i].Encoding.IsUnknown() {
			columns[i].Encoding = types.StringNull()
		}
		if columns[i].Nullable.IsUnknown() {
			columns[i].Nullable = types.BoolNull()
		}
	}
	if list, diagnostics := types.ListValueFrom(context.Background(), types.ObjectType{AttrTypes: tableColumnAttributeTypes}, columns); !diagnostics.HasError() {
		data.Columns = list
	}
	return data
}

// verify re-reads the table after Create or Update and stores it once the catalog matches the plan.
func (r *tableResource) verify(ctx context.Context, plan tableModel, state *tfsdk.State, diagnostics *diag.Diagnostics, absent string) {
	observed := plan
	found, _, err := r.read(ctx, &observed)
	switch {
	case err != nil:
		diagnostics.AddError("Verify table", err.Error())
		return
	case !found:
		diagnostics.AddError("Verify table", absent)
		return
	}
	planSpec, err := tableSpecOf(plan)
	if err == nil {
		var observedSpec tableSpec
		if observedSpec, err = tableSpecOf(observed); err == nil {
			err = tableConverged(planSpec, observedSpec)
		}
	}
	if err != nil {
		diagnostics.AddError("Verify table", "The catalog does not match the configuration after the change: "+err.Error())
		return
	}
	diagnostics.Append(state.Set(ctx, &observed)...)
}

// Create validates the definition, creates the table, transfers ownership, and verifies the catalog.
func (r *tableResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data tableModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	spec, err := tableSpecOf(data)
	var statements []string
	if err == nil {
		statements, err = createTableStatements(spec)
	}
	if err != nil {
		resp.Diagnostics.AddError("Invalid table", err.Error())
		return
	}
	database := data.Database.ValueString()
	if err := r.exec(ctx, database, statements[0]); err != nil {
		resp.Diagnostics.AddError("Create table", err.Error())
		return
	}
	data.ID = r.identity(database, map[string]string{"schema": spec.schema, "name": spec.name})
	// A failed ownership change or verification must still leave state for the created table.
	known := tableKnownState(data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &known)...)
	if err := r.exec(ctx, database, statements[1:]...); err != nil {
		resp.Diagnostics.AddError("Set table owner", err.Error())
		return
	}
	r.verify(ctx, data, &resp.State, &resp.Diagnostics, "The table is absent after creation.")
}

// ValidateConfig reports definitions Create would reject, during planning once the configuration is known.
func (r *tableResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data tableModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() || !req.Config.Raw.IsFullyKnown() {
		return
	}
	if _, err := tableSpecOf(data); err != nil {
		resp.Diagnostics.AddError("Invalid table", err.Error())
	}
}

// Read refreshes the definition or removes a table whose table, schema, or database is gone.
func (r *tableResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data tableModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	found, _, err := r.read(ctx, &data)
	switch {
	case err != nil:
		resp.Diagnostics.AddError("Read table", err.Error())
	case !found:
		resp.State.RemoveResource(ctx)
	default:
		resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	}
}

// Update applies the in-place changes from the table's current catalog definition and verifies the result.
func (r *tableResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, current tableModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &current)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := tableSpecOf(plan); err != nil {
		resp.Diagnostics.AddError("Invalid table", err.Error())
		return
	}
	found, constraints, err := r.read(ctx, &current)
	switch {
	case err != nil:
		resp.Diagnostics.AddError("Read table", err.Error())
		return
	case !found:
		resp.Diagnostics.AddError("Update table", "The table disappeared during the update; refresh the plan.")
		return
	}
	before, after, err := tableAlterStates(current, constraints, plan)
	database := plan.Database.ValueString()
	if err == nil {
		err = r.exec(ctx, database, tableAlterPhaseStatements(before, after, tablePhaseDropConstraints, tablePhaseAddColumns, tablePhaseKeys)...)
	}
	// ALTER SORTKEY can re-encode columns of the old and new key, so encodings are compared against the catalog
	// after the key change; the other phases still start from the definition before the update.
	encodings := before
	if err == nil && tableSortKeyReencodes(before.spec, after.spec) {
		encodings, err = r.refreshEncodings(ctx, plan)
	}
	if err == nil {
		err = r.exec(ctx, database, tableAlterPhaseStatements(encodings, after, tablePhaseAlterColumns)...)
	}
	if err == nil {
		err = r.exec(ctx, database, tableAlterPhaseStatements(before, after, tablePhaseDropColumns, tablePhaseRestoreKeys, tablePhaseAddConstraints, tablePhaseOwner)...)
	}
	if err != nil {
		resp.Diagnostics.AddError("Update table", err.Error())
		return
	}
	r.verify(ctx, plan, &resp.State, &resp.Diagnostics, "The table disappeared during the update.")
}

// refreshEncodings re-reads the table in the middle of an update, so the alter-columns phase starts from the
// encodings Redshift assigned during the sort key change.
func (r *tableResource) refreshEncodings(ctx context.Context, plan tableModel) (tableAlterState, error) {
	refreshed := plan
	found, names, err := r.read(ctx, &refreshed)
	switch {
	case err != nil:
		return tableAlterState{}, err
	case !found:
		return tableAlterState{}, fmt.Errorf("the table disappeared during the update")
	}
	spec, err := tableSpecOf(refreshed)
	if err != nil {
		return tableAlterState{}, fmt.Errorf("table definition after the sort key change: %w", err)
	}
	return tableAlterState{model: refreshed, spec: spec, constraints: names}, nil
}

// Delete drops the table without CASCADE and verifies its removal.
func (r *tableResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data tableModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	found, _, err := r.read(ctx, &data)
	if err == nil && found {
		err = r.exec(ctx, data.Database.ValueString(), dropTableStatement(tableSpec{schema: data.Schema.ValueString(), name: data.Name.ValueString()}))
		if err == nil {
			found, _, err = r.read(ctx, &data)
			if err == nil && found {
				resp.Diagnostics.AddError("Delete table", "The table remains after deletion.")
			}
		}
	}
	if err != nil {
		resp.Diagnostics.AddError("Delete table", err.Error())
	}
}

// ImportState restores the table's database, schema, and name from its JSON identity.
func (r *tableResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importIdentity(ctx, req, resp, "database", "schema", "name")
}
