package provider

import (
	"context"
	"fmt"
	"maps"
	"slices"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/netcheck-de/terraform-provider-redshift/internal/sqlclient"
)

// Keyword allowlists from the AWS CREATE TABLE and compression encoding references.
// https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html
// https://docs.aws.amazon.com/redshift/latest/dg/c_Compression_encodings.html
var (
	tableEncodings     = []sqlclient.Keyword{"AZ64", "BYTEDICT", "DELTA", "DELTA32K", "LZO", "MOSTLY8", "MOSTLY16", "MOSTLY32", "RAW", "RUNLENGTH", "TEXT255", "TEXT32K", "ZSTD"}
	tableDistStyles    = []sqlclient.Keyword{"AUTO", "EVEN", "KEY", "ALL"}
	tableSortKeyStyles = []sqlclient.Keyword{"AUTO", "COMPOUND", "INTERLEAVED"}
	tableBackupModes   = []sqlclient.Keyword{"YES", "NO"}
	// tableEncodingsBlockingResize are the encodings whose columns ALTER COLUMN TYPE refuses to resize.
	tableEncodingsBlockingResize = []sqlclient.Keyword{"BYTEDICT", "RUNLENGTH", "TEXT255", "TEXT32K"}
	// tableKeyTypes are the format_type() spellings, without modifiers, of the types CREATE TABLE allows for
	// distribution and sort key columns.
	tableKeyTypes = []string{
		"boolean", "real", "double precision", "smallint", "integer", "bigint", "numeric", "date", "time without time zone",
		"time with time zone", "timestamp without time zone", "timestamp with time zone", "character", "character varying",
	}
)

// Documented limits of CREATE TABLE.
const (
	tableMaxColumns            = 1600
	tableMaxCompoundSortKeys   = 400
	tableMaxInterleavedSortKey = 8
	// tableVarcharPrefix and tableVarbytePrefix are how format_type() and ColumnType spell the types ALTER COLUMN
	// TYPE can resize.
	tableVarcharPrefix = "character varying("
	tableVarbytePrefix = "varbyte("
)

// tableIdentitySpec is an IDENTITY or GENERATED BY DEFAULT AS IDENTITY column clause.
type tableIdentitySpec struct {
	// seed is the first generated value.
	seed int64
	// step is the increment between generated values.
	step int64
	// generatedByDefault lets inserts supply their own value.
	generatedByDefault bool
}

// tableColumnSpec is one validated column definition.
type tableColumnSpec struct {
	// name is the column name.
	name string
	// dataType is the canonical type, as format_type() reports it.
	dataType sqlclient.Keyword
	// encoding is the compression encoding, or "" when Redshift chooses it.
	encoding sqlclient.Keyword
	// nullable is nil when Redshift decides, for example for identity and primary-key columns.
	nullable *bool
	// defaultSQL is the DEFAULT expression, or "" without one.
	defaultSQL sqlclient.UserSQL
	// identity is nil for ordinary columns.
	identity *tableIdentitySpec
}

// tableForeignKeySpec is one FOREIGN KEY table constraint.
type tableForeignKeySpec struct {
	// columns are the referencing columns of this table.
	columns []string
	// refSchema and refTable name the referenced table.
	refSchema, refTable string
	// refColumns are the referenced columns, matched by position.
	refColumns []string
}

// tableSpec is a validated table definition that the renderers consume.
type tableSpec struct {
	// schema and name identify the table.
	schema, name string
	// owner is "" when the owner is not managed or not yet known.
	owner string
	// columns are in declaration order.
	columns []tableColumnSpec
	// primaryKey is empty without a primary key.
	primaryKey []string
	// unique holds the UNIQUE constraints, sorted for deterministic SQL.
	unique [][]string
	// foreignKeys holds the FOREIGN KEY constraints, sorted for deterministic SQL.
	foreignKeys []tableForeignKeySpec
	// distStyle is the resolved distribution style.
	distStyle sqlclient.Keyword
	// distKey is the distribution column of DISTSTYLE KEY.
	distKey string
	// sortStyle is the resolved sort key style.
	sortStyle sqlclient.Keyword
	// sortKey lists the sort key columns in order; empty for AUTO.
	sortKey []string
	// backup is "" when not configured.
	backup sqlclient.Keyword
}

// column returns the named column.
func (s tableSpec) column(name string) (tableColumnSpec, bool) {
	for _, column := range s.columns {
		if column.name == name {
			return column, true
		}
	}
	return tableColumnSpec{}, false
}

// constrained reports whether a column belongs to a primary key, unique, or foreign key constraint, which
// ALTER COLUMN TYPE refuses to resize.
func (s tableSpec) constrained(name string) bool {
	if slices.Contains(s.primaryKey, name) {
		return true
	}
	for _, unique := range s.unique {
		if slices.Contains(unique, name) {
			return true
		}
	}
	for _, foreignKey := range s.foreignKeys {
		if slices.Contains(foreignKey.columns, name) {
			return true
		}
	}
	return false
}

// tableKnownString returns a configured string, rejecting unknown values that the renderers cannot use.
func tableKnownString(value types.String, what string) (string, error) {
	if value.IsUnknown() {
		return "", fmt.Errorf("%s must be known", what)
	}
	return value.ValueString(), nil
}

// tableFolded rejects ASCII uppercase in a name. Redshift folds ASCII letters of standard and quoted identifiers to
// lowercase unless enable_case_sensitive_identifier is set, which the provider does not do, so a mixed-case name
// would be created under a different spelling than every catalog read binds and compares.
// https://docs.aws.amazon.com/redshift/latest/dg/r_names.html
func tableFolded(what string, names ...string) error {
	for _, name := range names {
		if strings.ContainsFunc(name, func(r rune) bool { return r >= 'A' && r <= 'Z' }) {
			return fmt.Errorf("%s %q contains uppercase letters, which Redshift folds to lowercase; use the lowercase name", what, name)
		}
	}
	return nil
}

// tableStringList returns the elements of a list of strings; null is empty and unknown values are rejected.
func tableStringList(value types.List, what string) ([]string, error) {
	if value.IsNull() {
		return nil, nil
	}
	if value.IsUnknown() {
		return nil, fmt.Errorf("%s must be known", what)
	}
	var values []string
	for _, element := range value.Elements() {
		text, ok := element.(types.String)
		if !ok || text.IsUnknown() || text.IsNull() {
			return nil, fmt.Errorf("%s must contain known names", what)
		}
		values = append(values, text.ValueString())
	}
	return values, nil
}

// tableKeyword resolves an optional choice: "" when unset or unknown, because computed choices are derived later.
func tableKeyword(value types.String, what string, allowed ...sqlclient.Keyword) (sqlclient.Keyword, error) {
	keyword, err := optOneOf(value, allowed...)
	if err != nil {
		return "", fmt.Errorf("%s: %w", what, err)
	}
	return keyword, nil
}

// tableSpecOf validates a model into the definition the renderers use. Computed values that are unknown, such as a
// planned owner or encoding, are left unset; unknown configured values are an error, because SQL needs them.
func tableSpecOf(data tableModel) (tableSpec, error) {
	ctx := context.Background()
	var spec tableSpec
	var err error
	if spec.schema, err = tableKnownString(data.Schema, "schema"); err != nil {
		return spec, err
	}
	if spec.name, err = tableKnownString(data.Name, "name"); err != nil {
		return spec, err
	}
	if spec.schema == "" || spec.name == "" {
		return spec, fmt.Errorf("schema and name must be nonempty")
	}
	spec.owner = knownString(data.Owner)
	if err := tableFolded("schema", spec.schema); err != nil {
		return spec, err
	}
	if err := tableFolded("name", spec.name); err != nil {
		return spec, err
	}
	if err := tableFolded("owner", spec.owner); err != nil {
		return spec, err
	}
	if data.Columns.IsUnknown() || data.Columns.IsNull() {
		return spec, fmt.Errorf("columns must be known")
	}
	var columns []tableColumnModel
	if diagnostics := data.Columns.ElementsAs(ctx, &columns, false); diagnostics.HasError() {
		return spec, fmt.Errorf("columns must be known")
	}
	if len(columns) == 0 || len(columns) > tableMaxColumns {
		return spec, fmt.Errorf("a table needs between 1 and %d columns", tableMaxColumns)
	}
	for index, model := range columns {
		column, err := tableColumnSpecOf(model)
		if err != nil {
			return spec, fmt.Errorf("columns[%d]: %w", index, err)
		}
		if _, duplicate := spec.column(column.name); duplicate {
			return spec, fmt.Errorf("column %q is declared twice", column.name)
		}
		spec.columns = append(spec.columns, column)
	}
	if spec.primaryKey, err = tableStringList(data.PrimaryKey, "primary_key"); err != nil {
		return spec, err
	}
	if err := spec.checkColumns("primary_key", spec.primaryKey); err != nil {
		return spec, err
	}
	for _, name := range spec.primaryKey {
		if column, _ := spec.column(name); column.nullable != nil && *column.nullable {
			return spec, fmt.Errorf("primary key column %q cannot be nullable", name)
		}
	}
	if spec.unique, err = tableUniqueOf(data.Unique); err != nil {
		return spec, err
	}
	for _, unique := range spec.unique {
		if err := spec.checkColumns("unique", unique); err != nil {
			return spec, err
		}
	}
	if spec.foreignKeys, err = tableForeignKeysOf(data.ForeignKeys); err != nil {
		return spec, err
	}
	for _, foreignKey := range spec.foreignKeys {
		if err := spec.checkColumns("foreign_keys.columns", foreignKey.columns); err != nil {
			return spec, err
		}
	}
	if err := spec.resolveDistribution(data); err != nil {
		return spec, err
	}
	if err := spec.resolveSortKey(data); err != nil {
		return spec, err
	}
	if spec.backup, err = tableKeyword(data.Backup, "backup", tableBackupModes...); err != nil {
		return spec, err
	}
	return spec, nil
}

// tableColumnSpecOf validates one column.
func tableColumnSpecOf(model tableColumnModel) (tableColumnSpec, error) {
	var column tableColumnSpec
	var err error
	if column.name, err = tableKnownString(model.Name, "name"); err != nil {
		return column, err
	}
	if column.name == "" {
		return column, fmt.Errorf("name must be nonempty")
	}
	if err := tableFolded("column name", column.name); err != nil {
		return column, err
	}
	text, err := tableKnownString(model.Type, "type")
	if err != nil {
		return column, err
	}
	if column.dataType, err = sqlclient.ColumnType(text); err != nil {
		return column, fmt.Errorf("column %q: %w", column.name, err)
	}
	if column.encoding, err = tableKeyword(model.Encoding, "encoding", tableEncodings...); err != nil {
		return column, fmt.Errorf("column %q: %w", column.name, err)
	}
	column.nullable = knownBool(model.Nullable)
	if model.Default.IsUnknown() {
		return column, fmt.Errorf("column %q: default must be known", column.name)
	}
	if !model.Default.IsNull() {
		if column.defaultSQL, err = sqlclient.CheckUserSQL(model.Default.ValueString()); err != nil {
			return column, fmt.Errorf("column %q default: %w", column.name, err)
		}
	}
	if model.Identity.IsUnknown() {
		return column, fmt.Errorf("column %q: identity must be known", column.name)
	}
	if model.Identity.IsNull() {
		return column, nil
	}
	var identity tableIdentityModel
	if diagnostics := model.Identity.As(context.Background(), &identity, basetypes.ObjectAsOptions{}); diagnostics.HasError() || identity.Seed.IsUnknown() || identity.Step.IsUnknown() || identity.GeneratedByDefault.IsUnknown() {
		return column, fmt.Errorf("column %q: identity must be known", column.name)
	}
	column.identity = &tableIdentitySpec{seed: identity.Seed.ValueInt64(), step: identity.Step.ValueInt64(), generatedByDefault: identity.GeneratedByDefault.ValueBool()}
	switch {
	case column.dataType != "integer" && column.dataType != "bigint":
		return column, fmt.Errorf("identity column %q must be INTEGER or BIGINT", column.name)
	case column.identity.step == 0:
		return column, fmt.Errorf("identity column %q needs a nonzero step", column.name)
	case column.defaultSQL != "":
		return column, fmt.Errorf("identity column %q cannot also have a default", column.name)
	case column.nullable != nil && *column.nullable:
		return column, fmt.Errorf("identity column %q is always NOT NULL", column.name)
	}
	return column, nil
}

// tableUniqueOf reads the UNIQUE column lists, sorted so SQL does not depend on set order.
func tableUniqueOf(value types.Set) ([][]string, error) {
	if value.IsNull() {
		return nil, nil
	}
	if value.IsUnknown() {
		return nil, fmt.Errorf("unique must be known")
	}
	var unique [][]string
	for _, element := range value.Elements() {
		list, ok := element.(types.List)
		if !ok {
			return nil, fmt.Errorf("unique must contain column lists")
		}
		columns, err := tableStringList(list, "unique")
		if err != nil {
			return nil, err
		}
		if len(columns) == 0 {
			return nil, fmt.Errorf("a unique constraint needs at least one column")
		}
		unique = append(unique, columns)
	}
	slices.SortFunc(unique, func(a, b []string) int { return strings.Compare(tableUniqueKey(a), tableUniqueKey(b)) })
	return unique, nil
}

// tableForeignKeysOf reads the FOREIGN KEY constraints, sorted so SQL does not depend on set order.
func tableForeignKeysOf(value types.Set) ([]tableForeignKeySpec, error) {
	if value.IsNull() {
		return nil, nil
	}
	if value.IsUnknown() {
		return nil, fmt.Errorf("foreign_keys must be known")
	}
	var models []tableForeignKeyModel
	if diagnostics := value.ElementsAs(context.Background(), &models, false); diagnostics.HasError() {
		return nil, fmt.Errorf("foreign_keys must be known")
	}
	var foreignKeys []tableForeignKeySpec
	for _, model := range models {
		var foreignKey tableForeignKeySpec
		var err error
		if foreignKey.columns, err = tableStringList(model.Columns, "foreign_keys.columns"); err != nil {
			return nil, err
		}
		if foreignKey.refColumns, err = tableStringList(model.ReferencesColumns, "foreign_keys.references_columns"); err != nil {
			return nil, err
		}
		if foreignKey.refSchema, err = tableKnownString(model.ReferencesSchema, "foreign_keys.references_schema"); err != nil {
			return nil, err
		}
		if foreignKey.refTable, err = tableKnownString(model.ReferencesTable, "foreign_keys.references_table"); err != nil {
			return nil, err
		}
		switch {
		case foreignKey.refSchema == "" || foreignKey.refTable == "":
			return nil, fmt.Errorf("a foreign key needs a nonempty references_schema and references_table")
		case len(foreignKey.refColumns) != len(foreignKey.columns):
			return nil, fmt.Errorf("a foreign key needs as many references_columns as columns")
		}
		if err := tableDistinctNames("foreign_keys.references_columns", foreignKey.refColumns); err != nil {
			return nil, err
		}
		if err := tableFolded("foreign_keys reference", append([]string{foreignKey.refSchema, foreignKey.refTable}, foreignKey.refColumns...)...); err != nil {
			return nil, err
		}
		foreignKeys = append(foreignKeys, foreignKey)
	}
	slices.SortFunc(foreignKeys, func(a, b tableForeignKeySpec) int {
		return strings.Compare(tableForeignKeyKey(a), tableForeignKeyKey(b))
	})
	return foreignKeys, nil
}

// tableDistinctNames rejects empty and repeated names in one column list.
func tableDistinctNames(what string, names []string) error {
	seen := map[string]bool{}
	for _, name := range names {
		if name == "" || seen[name] {
			return fmt.Errorf("%s must list distinct nonempty names", what)
		}
		seen[name] = true
	}
	return nil
}

// checkColumns requires a constraint or key list to name distinct columns of this table. A configured but empty
// list is allowed for optional lists and means none.
func (s tableSpec) checkColumns(what string, names []string) error {
	if err := tableDistinctNames(what, names); err != nil {
		return err
	}
	for _, name := range names {
		if _, ok := s.column(name); !ok {
			return fmt.Errorf("%s names column %q, which the table does not declare", what, name)
		}
	}
	return nil
}

// resolveDistribution derives the distribution style the plan modifier would choose and checks it against the key.
func (s *tableSpec) resolveDistribution(data tableModel) error {
	var err error
	if s.distStyle, err = tableKeyword(data.DistStyle, "diststyle", tableDistStyles...); err != nil {
		return err
	}
	if s.distKey, err = tableKnownString(data.DistKey, "distkey"); err != nil {
		return err
	}
	if s.distStyle == "" {
		s.distStyle = "AUTO"
		if s.distKey != "" {
			s.distStyle = "KEY"
		}
	}
	switch {
	case s.distStyle == "KEY" && s.distKey == "":
		return fmt.Errorf("diststyle KEY needs a distkey")
	case s.distStyle != "KEY" && s.distKey != "":
		return fmt.Errorf("distkey requires diststyle KEY")
	}
	if s.distKey != "" {
		return s.checkKeyColumns("distkey", []string{s.distKey})
	}
	return nil
}

// resolveSortKey derives the sort key style the plan modifier would choose and checks the column count limits.
func (s *tableSpec) resolveSortKey(data tableModel) error {
	var err error
	if s.sortStyle, err = tableKeyword(data.SortKeyStyle, "sortkey_style", tableSortKeyStyles...); err != nil {
		return err
	}
	if s.sortKey, err = tableStringList(data.SortKey, "sortkey"); err != nil {
		return err
	}
	if s.sortStyle == "" {
		s.sortStyle = "AUTO"
		if len(s.sortKey) > 0 {
			s.sortStyle = "COMPOUND"
		}
	}
	switch {
	case s.sortStyle == "AUTO" && len(s.sortKey) > 0:
		return fmt.Errorf("sortkey_style AUTO lets Redshift choose the sort key; remove sortkey")
	case s.sortStyle != "AUTO" && len(s.sortKey) == 0:
		return fmt.Errorf("sortkey_style %s needs sortkey columns", s.sortStyle)
	case s.sortStyle == "COMPOUND" && len(s.sortKey) > tableMaxCompoundSortKeys:
		return fmt.Errorf("a compound sort key has at most %d columns", tableMaxCompoundSortKeys)
	case s.sortStyle == "INTERLEAVED" && len(s.sortKey) > tableMaxInterleavedSortKey:
		return fmt.Errorf("an interleaved sort key has at most %d columns", tableMaxInterleavedSortKey)
	}
	return s.checkKeyColumns("sortkey", s.sortKey)
}

// checkKeyColumns requires distribution and sort key columns to exist and to have a type CREATE TABLE allows for
// keys, so SUPER, VARBYTE, GEOMETRY, and similar keys fail during planning instead of in CREATE or ALTER TABLE.
// https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html
func (s tableSpec) checkKeyColumns(what string, names []string) error {
	if err := s.checkColumns(what, names); err != nil {
		return err
	}
	for _, name := range names {
		column, _ := s.column(name)
		base, _, _ := strings.Cut(string(column.dataType), "(")
		if !slices.Contains(tableKeyTypes, base) {
			return fmt.Errorf("%s column %q has type %s, which Redshift does not allow in a key", what, name, column.dataType)
		}
	}
	return nil
}

// tableNames renders a parenthesized column list.
func tableNames(names []string) []sqlclient.Statement {
	items := make([]sqlclient.Statement, len(names))
	for i, name := range names {
		items[i] = sqlclient.Ident(name)
	}
	return items
}

// tableColumnDefinition renders a column in the attribute order of the CREATE TABLE synopsis: DEFAULT, IDENTITY,
// ENCODE, then the NOT NULL constraint. Nullable columns stay implicit, because NULL is the default.
func tableColumnDefinition(column tableColumnSpec) sqlclient.Statement {
	definition := sqlclient.Ident(column.name).Kw(column.dataType).
		When(column.defaultSQL != "", func(s sqlclient.Statement) sqlclient.Statement { return s.Kw("DEFAULT").Verbatim(column.defaultSQL) })
	if identity := column.identity; identity != nil {
		clause := sqlclient.Keyword("IDENTITY")
		if identity.generatedByDefault {
			clause = "GENERATED BY DEFAULT AS IDENTITY"
		}
		definition = definition.Kw(clause).Args(sqlclient.Int(identity.seed), sqlclient.Int(identity.step))
	}
	return definition.When(column.encoding != "", func(s sqlclient.Statement) sqlclient.Statement { return s.Kw("ENCODE", column.encoding) }).
		If(column.nullable != nil && !*column.nullable, "NOT NULL")
}

// tableForeignKeyClause renders FOREIGN KEY (columns) REFERENCES schema.table (columns).
func tableForeignKeyClause(foreignKey tableForeignKeySpec) sqlclient.Statement {
	return sqlclient.Kw("FOREIGN KEY").Paren(tableNames(foreignKey.columns)...).
		KwQualified("REFERENCES", foreignKey.refSchema, foreignKey.refTable).Paren(tableNames(foreignKey.refColumns)...)
}

// tableSortKeyClause renders the table attribute of a sort key style.
func tableSortKeyClause(style sqlclient.Keyword, columns []string) sqlclient.Statement {
	if style == "AUTO" {
		return sqlclient.Kw("SORTKEY AUTO")
	}
	return sqlclient.Kw(style, "SORTKEY").Paren(tableNames(columns)...)
}

// createTableStatements renders CREATE TABLE with every column, constraint, and table attribute spelled out, so
// creation never depends on server defaults, and then the owner change, because CREATE TABLE always makes the
// executing user the owner.
func createTableStatements(spec tableSpec) ([]string, error) {
	items := make([]sqlclient.Statement, 0, len(spec.columns)+1+len(spec.unique)+len(spec.foreignKeys))
	for _, column := range spec.columns {
		items = append(items, tableColumnDefinition(column))
	}
	if len(spec.primaryKey) > 0 {
		items = append(items, sqlclient.Kw("PRIMARY KEY").Paren(tableNames(spec.primaryKey)...))
	}
	for _, unique := range spec.unique {
		items = append(items, sqlclient.Kw("UNIQUE").Paren(tableNames(unique)...))
	}
	for _, foreignKey := range spec.foreignKeys {
		items = append(items, tableForeignKeyClause(foreignKey))
	}
	create := sqlclient.Stmt("CREATE TABLE").Qualified(spec.schema, spec.name).Paren(items...).
		When(spec.backup != "", func(s sqlclient.Statement) sqlclient.Statement { return s.Kw("BACKUP", spec.backup) }).
		Kw("DISTSTYLE", spec.distStyle).
		When(spec.distStyle == "KEY", func(s sqlclient.Statement) sqlclient.Statement {
			return s.Kw("DISTKEY").Paren(sqlclient.Ident(spec.distKey))
		}).
		Append(tableSortKeyClause(spec.sortStyle, spec.sortKey))
	if err := create.Err(); err != nil {
		return nil, err
	}
	statements := []string{create.String()}
	if spec.owner != "" {
		statements = append(statements, tableAlter(spec).KwIdent("OWNER TO", spec.owner).String())
	}
	return statements, nil
}

// tableAlter starts every ALTER TABLE statement for the table.
func tableAlter(spec tableSpec) sqlclient.Statement {
	return sqlclient.Stmt("ALTER TABLE").Qualified(spec.schema, spec.name)
}

// dropTableStatement renders DROP TABLE without CASCADE, so dependent views and referencing foreign keys keep the
// table, and the deletion fails instead of removing objects Terraform does not manage.
func dropTableStatement(spec tableSpec) string {
	return sqlclient.Stmt("DROP TABLE").Qualified(spec.schema, spec.name).String()
}

// tableUniqueKey identifies a UNIQUE constraint by its ordered columns.
func tableUniqueKey(columns []string) string {
	return "u:" + strings.Join(columns, "\x00")
}

// tableForeignKeyKey identifies a FOREIGN KEY constraint by its columns and referenced columns.
func tableForeignKeyKey(foreignKey tableForeignKeySpec) string {
	return "f:" + strings.Join([]string{strings.Join(foreignKey.columns, "\x00"), foreignKey.refSchema, foreignKey.refTable, strings.Join(foreignKey.refColumns, "\x00")}, "\x01")
}

// tablePrimaryKeyKey identifies the primary key, of which a table has at most one.
const tablePrimaryKeyKey = "p"

// tableDefaultCanonical normalizes a default expression for comparison: the catalog adds casts such as
// ::character varying and changes spacing and case, which do not change the default.
func tableDefaultCanonical(text string) string {
	var out strings.Builder
	quoted := false
	for i := 0; i < len(text); i++ {
		char := text[i]
		switch {
		case char == '\'':
			quoted = !quoted
			out.WriteByte(char)
		case quoted:
			out.WriteByte(char)
		case char == ' ' || char == '\t' || char == '\n' || char == '\r':
		default:
			out.WriteString(strings.ToLower(string(char)))
		}
	}
	canonical := tableCastPattern.ReplaceAllString(out.String(), "")
	for len(canonical) >= 2 && canonical[0] == '(' && canonical[len(canonical)-1] == ')' && tableBalanced(canonical[1:len(canonical)-1]) {
		canonical = canonical[1 : len(canonical)-1]
	}
	return canonical
}

// tableBalanced reports whether parentheses outside literals stay balanced, so stripping an outer pair is safe.
func tableBalanced(text string) bool {
	depth, quoted := 0, false
	for _, char := range text {
		switch {
		case char == '\'':
			quoted = !quoted
		case quoted:
		case char == '(':
			depth++
		case char == ')':
			depth--
			if depth < 0 {
				return false
			}
		}
	}
	return depth == 0
}

// tableDefaultsEqual compares two default expressions after canonicalization.
func tableDefaultsEqual(a, b sqlclient.UserSQL) bool {
	return tableDefaultCanonical(string(a)) == tableDefaultCanonical(string(b))
}

// tableColumnDiff lists the in-place column changes between two definitions, or why they need replacement.
type tableColumnDiff struct {
	// added are the new trailing columns.
	added []tableColumnSpec
	// dropped are the removed columns.
	dropped []string
	// encoded are retained columns whose encoding changes.
	encoded []tableColumnSpec
	// widened are retained VARCHAR or VARBYTE columns whose length grows.
	widened []tableColumnSpec
	// replace explains a change ALTER TABLE cannot make; empty when every change is in place.
	replace string
}

// tableResizableLength splits a canonical VARCHAR or VARBYTE type into its family and declared length; ALTER COLUMN
// TYPE can only grow those. https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE_examples_basic.html
func tableResizableLength(dataType sqlclient.Keyword) (string, int64, bool) {
	text := string(dataType)
	for _, family := range []string{tableVarcharPrefix, tableVarbytePrefix} {
		if !strings.HasPrefix(text, family) || !strings.HasSuffix(text, ")") {
			continue
		}
		length, err := strconv.ParseInt(text[len(family):len(text)-1], 10, 64)
		return family, length, err == nil
	}
	return "", 0, false
}

// tableIdentityEqual compares identity clauses, including their absence.
func tableIdentityEqual(a, b *tableIdentitySpec) bool {
	if a == nil || b == nil {
		return a == b
	}
	return *a == *b
}

// tableColumnChanges classifies column changes against the ALTER TABLE limits: columns are added only at the end,
// never as identity columns, and as NOT NULL only with a default, only VARCHAR and VARBYTE columns without defaults, constraints, or BYTEDICT, RUNLENGTH,
// TEXT255, or TEXT32K encoding are widened, and encodings change only outside interleaved sort keys.
// https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html
func tableColumnChanges(prev, plan tableSpec) tableColumnDiff {
	var diff tableColumnDiff
	lastRetained := -1
	for _, column := range plan.columns {
		before, retained := prev.column(column.name)
		if !retained {
			if column.identity != nil {
				diff.replace = fmt.Sprintf("ALTER TABLE ADD COLUMN cannot add the identity column %q", column.name)
				return diff
			}
			// Existing rows would hold NULL in the new column, so Redshift refuses ADD COLUMN ... NOT NULL without
			// a DEFAULT; this includes new primary key columns, which are NOT NULL.
			if column.nullable != nil && !*column.nullable && column.defaultSQL == "" {
				diff.replace = fmt.Sprintf("ALTER TABLE ADD COLUMN cannot add the NOT NULL column %q without a default", column.name)
				return diff
			}
			diff.added = append(diff.added, column)
			continue
		}
		position := slices.IndexFunc(prev.columns, func(c tableColumnSpec) bool { return c.name == column.name })
		if position < lastRetained || len(diff.added) > 0 {
			diff.replace = fmt.Sprintf("columns can only be added at the end and existing columns keep their order (%q)", column.name)
			return diff
		}
		lastRetained = position
		if reason := tableColumnChange(prev, plan, before, column); reason != "" {
			diff.replace = reason
			return diff
		}
		if before.dataType != column.dataType {
			diff.widened = append(diff.widened, column)
		}
		if before.encoding != "" && column.encoding != "" && before.encoding != column.encoding {
			diff.encoded = append(diff.encoded, column)
		}
	}
	for _, column := range prev.columns {
		if _, kept := plan.column(column.name); !kept {
			diff.dropped = append(diff.dropped, column.name)
		}
	}
	return diff
}

// tableColumnChange explains why a retained column cannot change in place, or returns "".
func tableColumnChange(prev, plan tableSpec, before, after tableColumnSpec) string {
	switch {
	case before.nullable != nil && after.nullable != nil && *before.nullable != *after.nullable:
		return fmt.Sprintf("Redshift cannot change the nullability of column %q", after.name)
	case (before.defaultSQL == "") != (after.defaultSQL == "") || !tableDefaultsEqual(before.defaultSQL, after.defaultSQL):
		return fmt.Sprintf("Redshift cannot change the default of column %q", after.name)
	case !tableIdentityEqual(before.identity, after.identity):
		return fmt.Sprintf("Redshift cannot change the identity of column %q", after.name)
	case before.encoding != "" && after.encoding != "" && before.encoding != after.encoding && plan.sortStyle == "INTERLEAVED":
		return fmt.Sprintf("Redshift cannot change the encoding of column %q in a table with an interleaved sort key", after.name)
	}
	if before.dataType == after.dataType {
		return ""
	}
	fromFamily, from, fromResizable := tableResizableLength(before.dataType)
	toFamily, to, toResizable := tableResizableLength(after.dataType)
	switch {
	case !fromResizable || !toResizable || fromFamily != toFamily || to < from:
		return fmt.Sprintf("Redshift can only widen VARCHAR and VARBYTE columns in place, not change %q from %s to %s", after.name, before.dataType, after.dataType)
	case before.defaultSQL != "":
		return fmt.Sprintf("Redshift cannot resize column %q, which has a default", after.name)
	case prev.constrained(after.name) || plan.constrained(after.name):
		return fmt.Sprintf("Redshift cannot resize column %q, which belongs to a constraint", after.name)
	case slices.Contains(tableEncodingsBlockingResize, before.encoding):
		return fmt.Sprintf("Redshift cannot resize column %q with %s encoding", after.name, before.encoding)
	}
	return ""
}

// tableReplacements explains, per attribute, the changes from prev to plan that ALTER TABLE cannot make.
func tableReplacements(prev, plan tableSpec) map[string]string {
	reasons := map[string]string{}
	if reason := tableColumnChanges(prev, plan).replace; reason != "" {
		reasons["columns"] = reason
	}
	if !slices.Equal(prev.primaryKey, plan.primaryKey) {
		for _, name := range plan.primaryKey {
			if column, existed := prev.column(name); existed && (column.nullable == nil || *column.nullable) {
				reasons["primary_key"] = fmt.Sprintf("ALTER TABLE cannot add a primary key on the nullable column %q", name)
			}
		}
	}
	// ALTER DISTSTYLE, ALTER DISTKEY, and ALTER COMPOUND SORTKEY cannot produce or operate on an interleaved
	// sort key; a table leaving an interleaved sort key changes it first.
	if plan.sortStyle == "INTERLEAVED" {
		interleaved := "ALTER TABLE cannot change distribution or create an interleaved sort key in place"
		if prev.distStyle != plan.distStyle {
			reasons["diststyle"] = interleaved
		}
		if prev.distKey != plan.distKey {
			reasons["distkey"] = interleaved
		}
		if prev.sortStyle != plan.sortStyle {
			reasons["sortkey_style"] = interleaved
		}
		if !slices.Equal(prev.sortKey, plan.sortKey) {
			reasons["sortkey"] = interleaved
		}
	}
	if prev.backup != "" && plan.backup != "" && prev.backup != plan.backup {
		reasons["backup"] = "ALTER TABLE cannot change BACKUP"
	}
	return reasons
}

// tableAlterState is one side of an update: the model, its validated definition, and the catalog names of its
// constraints, which DROP CONSTRAINT needs.
type tableAlterState struct {
	// model holds the Terraform values the alter steps compare.
	model tableModel
	// spec is the validated definition the steps render.
	spec tableSpec
	// constraints maps constraint keys to catalog names; only the prior side needs them.
	constraints map[string]string
}

// tableAlterPhase orders the statements of an update: constraints are dropped before the columns they use,
// columns are added before keys reference them, keys move off columns before those are dropped, and
// constraints are added last.
type tableAlterPhase int

const (
	// tablePhaseDropConstraints drops removed or changed constraints.
	tablePhaseDropConstraints tableAlterPhase = iota
	// tablePhaseAddColumns adds trailing columns.
	tablePhaseAddColumns
	// tablePhaseKeys changes the sort key, then the distribution, so a table leaving an interleaved sort key
	// can be redistributed.
	tablePhaseKeys
	// tablePhaseAlterColumns changes encodings and widens VARCHAR columns.
	tablePhaseAlterColumns
	// tablePhaseDropColumns drops removed columns.
	tablePhaseDropColumns
	// tablePhaseRestoreKeys returns keys to AUTO after tablePhaseKeys moved them off a dropped column or an
	// interleaved sort key, because ALTER SORTKEY AUTO and ALTER DISTSTYLE AUTO keep the current key.
	tablePhaseRestoreKeys
	// tablePhaseAddConstraints adds new constraints, the primary key first so foreign keys can reference it.
	tablePhaseAddConstraints
	// tablePhaseOwner transfers ownership last, so the earlier statements still run as the owner.
	tablePhaseOwner
)

// tableAlterPhases lists the phases in execution order.
var tableAlterPhases = []tableAlterPhase{tablePhaseDropConstraints, tablePhaseAddColumns, tablePhaseKeys, tablePhaseAlterColumns, tablePhaseDropColumns, tablePhaseRestoreKeys, tablePhaseAddConstraints, tablePhaseOwner}

// tableSortKeyChanged reports a sort key change, after which Redshift may re-encode columns of the old and new key.
func tableSortKeyChanged(prev, plan tableSpec) bool {
	return prev.sortStyle != plan.sortStyle || !slices.Equal(prev.sortKey, plan.sortKey)
}

// tableSortKeyReencodes reports a sort key change that runs ALTER COMPOUND SORTKEY or ALTER SORTKEY NONE, after
// which the encodings of the old and new key columns are unknown; ALTER SORTKEY AUTO alone keeps the key.
func tableSortKeyReencodes(prev, plan tableSpec) bool {
	return tableSortKeyChanged(prev, plan) && (plan.sortStyle != "AUTO" || tableSortKeyDetour(prev, plan))
}

// tableDropsAny reports whether the update drops one of names.
func tableDropsAny(prev, plan tableSpec, names ...string) bool {
	return slices.ContainsFunc(names, func(name string) bool {
		_, kept := plan.column(name)
		return name != "" && !kept
	})
}

// tableSortKeyDetour reports a move to SORTKEY AUTO that must first remove the sort key: ALTER SORTKEY AUTO keeps
// the current key, which can be neither interleaved, since only a compound key or none may follow one, nor on a
// column the update drops. https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html
func tableSortKeyDetour(prev, plan tableSpec) bool {
	return plan.sortStyle == "AUTO" && (prev.sortStyle == "INTERLEAVED" || tableDropsAny(prev, plan, prev.sortKey...))
}

// tableDistributionDetour reports a move to DISTSTYLE AUTO from a key the update drops: ALTER DISTSTYLE AUTO keeps
// the distribution key of a large table, and DROP COLUMN refuses the distribution key.
func tableDistributionDetour(prev, plan tableSpec) bool {
	return plan.distStyle == "AUTO" && prev.distStyle == "KEY" && tableDropsAny(prev, plan, prev.distKey)
}

// tableSortKeyStatements renders the sort key change of one phase; interleaved targets are replaced instead. A
// detour removes the key with ALTER SORTKEY NONE first and sets AUTO once the columns are dropped.
func tableSortKeyStatements(phase tableAlterPhase, prev, plan tableAlterState) []string {
	if !tableSortKeyChanged(prev.spec, plan.spec) {
		return nil
	}
	alter := tableAlter(plan.spec)
	detour := tableSortKeyDetour(prev.spec, plan.spec)
	switch {
	case phase == tablePhaseRestoreKeys && detour:
		return []string{alter.Kw("ALTER SORTKEY AUTO").String()}
	case phase != tablePhaseKeys:
		return nil
	case detour:
		return []string{alter.Kw("ALTER SORTKEY NONE").String()}
	case plan.spec.sortStyle == "AUTO":
		return []string{alter.Kw("ALTER SORTKEY AUTO").String()}
	}
	return []string{alter.Kw("ALTER COMPOUND SORTKEY").Paren(tableNames(plan.spec.sortKey)...).String()}
}

// tableDistributionStatements renders the distribution change of one phase. A detour distributes EVEN until the
// old key column is dropped and sets AUTO afterwards.
func tableDistributionStatements(phase tableAlterPhase, prev, plan tableAlterState) []string {
	if prev.spec.distStyle == plan.spec.distStyle && prev.spec.distKey == plan.spec.distKey {
		return nil
	}
	alter := tableAlter(plan.spec)
	detour := tableDistributionDetour(prev.spec, plan.spec)
	switch {
	case phase == tablePhaseRestoreKeys && detour:
		return []string{alter.Kw("ALTER DISTSTYLE AUTO").String()}
	case phase != tablePhaseKeys:
		return nil
	case detour:
		return []string{alter.Kw("ALTER DISTSTYLE EVEN").String()}
	case plan.spec.distStyle != "KEY":
		return []string{alter.Kw("ALTER DISTSTYLE", plan.spec.distStyle).String()}
	case prev.spec.distStyle == "KEY":
		return []string{alter.Kw("ALTER DISTKEY").Ident(plan.spec.distKey).String()}
	default:
		return []string{alter.Kw("ALTER DISTSTYLE KEY DISTKEY").Ident(plan.spec.distKey).String()}
	}
}

// tableConstraintChanges renders the drops or additions of one constraint kind, given each side's keyed clauses;
// drops look the catalog name up in prev's constraint names.
func tableConstraintChanges(phase tableAlterPhase, prev, plan tableAlterState, before, after map[string]sqlclient.Statement) []string {
	var statements []string
	if phase == tablePhaseDropConstraints {
		for _, key := range slices.Sorted(maps.Keys(before)) {
			if _, kept := after[key]; !kept {
				statements = append(statements, tableAlter(plan.spec).Kw("DROP CONSTRAINT").Ident(prev.constraints[tableConstraintKey(key)]).String())
			}
		}
		return statements
	}
	if phase == tablePhaseAddConstraints {
		for _, key := range slices.Sorted(maps.Keys(after)) {
			if _, existed := before[key]; !existed {
				statements = append(statements, tableAlter(plan.spec).Kw("ADD").Append(after[key]).String())
			}
		}
	}
	return statements
}

// tablePrimaryKeyClauses keys the primary key clause of a definition.
func tablePrimaryKeyClauses(spec tableSpec) map[string]sqlclient.Statement {
	clauses := map[string]sqlclient.Statement{}
	if len(spec.primaryKey) > 0 {
		// The key includes the columns, so a changed primary key is dropped and added again.
		clauses[tablePrimaryKeyKey+":"+strings.Join(spec.primaryKey, "\x00")] = sqlclient.Kw("PRIMARY KEY").Paren(tableNames(spec.primaryKey)...)
	}
	return clauses
}

// tableUniqueClauses keys the UNIQUE clauses of a definition.
func tableUniqueClauses(spec tableSpec) map[string]sqlclient.Statement {
	clauses := map[string]sqlclient.Statement{}
	for _, unique := range spec.unique {
		clauses[tableUniqueKey(unique)] = sqlclient.Kw("UNIQUE").Paren(tableNames(unique)...)
	}
	return clauses
}

// tableForeignKeyClauses keys the FOREIGN KEY clauses of a definition.
func tableForeignKeyClauses(spec tableSpec) map[string]sqlclient.Statement {
	clauses := map[string]sqlclient.Statement{}
	for _, foreignKey := range spec.foreignKeys {
		clauses[tableForeignKeyKey(foreignKey)] = tableForeignKeyClause(foreignKey)
	}
	return clauses
}

// tableConstraintKey maps a primary-key clause key to the catalog lookup key, which ignores its columns because
// a table has one primary key.
func tableConstraintKey(key string) string {
	if strings.HasPrefix(key, tablePrimaryKeyKey+":") {
		return tablePrimaryKeyKey
	}
	return key
}

// tableAlterSteps returns the alter steps for one phase. Every in-place attribute has one step; a step renders only
// the part of its change that belongs to the phase, and the constraint phases order the kinds so foreign keys go
// first when dropped and last when added.
func tableAlterSteps(phase tableAlterPhase) []alterStep[tableAlterState] {
	steps := map[string]alterStep[tableAlterState]{
		"columns": {attribute: "columns", value: func(s tableAlterState) attr.Value { return s.model.Columns }, render: func(prev, plan tableAlterState) []string {
			diff := tableColumnChanges(prev.spec, plan.spec)
			alter := tableAlter(plan.spec)
			var statements []string
			switch phase {
			case tablePhaseAddColumns:
				for _, column := range diff.added {
					statements = append(statements, alter.Kw("ADD COLUMN").Append(tableColumnDefinition(column)).String())
				}
			case tablePhaseAlterColumns:
				for _, column := range diff.widened {
					statements = append(statements, alter.Kw("ALTER COLUMN").Ident(column.name).Kw("TYPE", column.dataType).String())
				}
				for _, column := range diff.encoded {
					statements = append(statements, alter.Kw("ALTER COLUMN").Ident(column.name).Kw("ENCODE", column.encoding).String())
				}
			case tablePhaseDropColumns:
				for _, name := range diff.dropped {
					statements = append(statements, alter.Kw("DROP COLUMN").Ident(name).String())
				}
			}
			return statements
		}},
		"primary_key": {attribute: "primary_key", value: func(s tableAlterState) attr.Value { return s.model.PrimaryKey }, render: func(prev, plan tableAlterState) []string {
			return tableConstraintChanges(phase, prev, plan, tablePrimaryKeyClauses(prev.spec), tablePrimaryKeyClauses(plan.spec))
		}},
		"unique": {attribute: "unique", value: func(s tableAlterState) attr.Value { return s.model.Unique }, render: func(prev, plan tableAlterState) []string {
			return tableConstraintChanges(phase, prev, plan, tableUniqueClauses(prev.spec), tableUniqueClauses(plan.spec))
		}},
		"foreign_keys": {attribute: "foreign_keys", value: func(s tableAlterState) attr.Value { return s.model.ForeignKeys }, render: func(prev, plan tableAlterState) []string {
			return tableConstraintChanges(phase, prev, plan, tableForeignKeyClauses(prev.spec), tableForeignKeyClauses(plan.spec))
		}},
		// Style and columns are one statement; the style step renders it, and the column step only when the
		// style is unchanged, so a change of both is not issued twice.
		"sortkey_style": {attribute: "sortkey_style", value: func(s tableAlterState) attr.Value { return s.model.SortKeyStyle }, render: func(prev, plan tableAlterState) []string {
			return tableSortKeyStatements(phase, prev, plan)
		}},
		"sortkey": {attribute: "sortkey", value: func(s tableAlterState) attr.Value { return s.model.SortKey }, render: func(prev, plan tableAlterState) []string {
			if prev.spec.sortStyle != plan.spec.sortStyle {
				return nil
			}
			return tableSortKeyStatements(phase, prev, plan)
		}},
		"diststyle": {attribute: "diststyle", value: func(s tableAlterState) attr.Value { return s.model.DistStyle }, render: func(prev, plan tableAlterState) []string {
			return tableDistributionStatements(phase, prev, plan)
		}},
		"distkey": {attribute: "distkey", value: func(s tableAlterState) attr.Value { return s.model.DistKey }, render: func(prev, plan tableAlterState) []string {
			if prev.spec.distStyle != plan.spec.distStyle {
				return nil
			}
			return tableDistributionStatements(phase, prev, plan)
		}},
		"owner": {attribute: "owner", value: func(s tableAlterState) attr.Value { return s.model.Owner }, render: func(_, plan tableAlterState) []string {
			if phase != tablePhaseOwner || plan.spec.owner == "" {
				return nil
			}
			return []string{tableAlter(plan.spec).KwIdent("OWNER TO", plan.spec.owner).String()}
		}},
		// BACKUP has no ALTER TABLE form; the attribute changes in place only when nothing was recorded before,
		// as after import, and then nothing needs to run.
		"backup": {attribute: "backup", value: func(s tableAlterState) attr.Value { return s.model.Backup }, render: func(_, _ tableAlterState) []string { return nil }},
	}
	order := []string{"foreign_keys", "unique", "primary_key", "columns", "sortkey_style", "sortkey", "diststyle", "distkey", "owner", "backup"}
	if phase == tablePhaseAddConstraints {
		order = []string{"primary_key", "unique", "foreign_keys", "columns", "sortkey_style", "sortkey", "diststyle", "distkey", "owner", "backup"}
	}
	ordered := make([]alterStep[tableAlterState], 0, len(order))
	for _, name := range order {
		ordered = append(ordered, steps[name])
	}
	return ordered
}

// tableAlterStates validates both sides of an in-place update. prev comes from a fresh read, so the statements start
// from what Redshift holds; constraints maps prev's constraint keys to their catalog names. A change ALTER TABLE
// cannot make is an error, because the plan should have replaced the table.
func tableAlterStates(prev tableModel, constraints map[string]string, plan tableModel) (tableAlterState, tableAlterState, error) {
	prevSpec, err := tableSpecOf(prev)
	if err != nil {
		return tableAlterState{}, tableAlterState{}, fmt.Errorf("current table definition: %w", err)
	}
	planSpec, err := tableSpecOf(plan)
	if err != nil {
		return tableAlterState{}, tableAlterState{}, err
	}
	if reasons := tableReplacements(prevSpec, planSpec); len(reasons) > 0 {
		var messages []string
		for _, attribute := range slices.Sorted(maps.Keys(reasons)) {
			messages = append(messages, attribute+": "+reasons[attribute])
		}
		return tableAlterState{}, tableAlterState{}, fmt.Errorf("the change requires replacing the table: %s", strings.Join(messages, "; "))
	}
	for _, clauses := range []func(tableSpec) map[string]sqlclient.Statement{tablePrimaryKeyClauses, tableUniqueClauses, tableForeignKeyClauses} {
		kept := clauses(planSpec)
		for key := range clauses(prevSpec) {
			if _, ok := kept[key]; !ok && constraints[tableConstraintKey(key)] == "" {
				return tableAlterState{}, tableAlterState{}, fmt.Errorf("the catalog reports no name for a constraint the update must drop")
			}
		}
	}
	return tableAlterState{model: prev, spec: prevSpec, constraints: constraints}, tableAlterState{model: plan, spec: planSpec}, nil
}

// tableAlterPhaseStatements renders the statements of the given phases in order.
func tableAlterPhaseStatements(before, after tableAlterState, phases ...tableAlterPhase) []string {
	var statements []string
	for _, phase := range phases {
		statements = append(statements, alterStatements(before, after, tableAlterSteps(phase))...)
	}
	return statements
}

// alterTableStatements renders the whole in-place update from the catalog's current definition to the plan, as
// Update runs it when the sort key stays; tableAlterStates explains the arguments.
func alterTableStatements(prev tableModel, constraints map[string]string, plan tableModel) ([]string, error) {
	before, after, err := tableAlterStates(prev, constraints, plan)
	if err != nil {
		return nil, err
	}
	return tableAlterPhaseStatements(before, after, tableAlterPhases...), nil
}

// readTableQuery reads the table's owner and declared distribution style from pg_class. reldiststyle is 0 for
// EVEN, 1 for KEY, 8 for ALL, and 9 for AUTO, whatever AUTO(ALL), AUTO(EVEN), or AUTO(KEY) Redshift currently
// applies. https://docs.aws.amazon.com/redshift/latest/dg/r_PG_CLASS_INFO.html
func readTableQuery(spec tableSpec) sqlclient.Query {
	return sqlclient.Select("c.relname AS table_name", "u.usename AS owner", "c.reldiststyle AS diststyle").
		From("pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace LEFT JOIN pg_user u ON u.usesysid = c.relowner").
		Where("n.nspname = :schema", sqlclient.Bind("schema", spec.schema)).
		Where("c.relname = :name", sqlclient.Bind("name", spec.name)).
		Where("c.relkind = 'r'")
}

// readTableAttributesQuery reads column order, canonical types, and nullability from pg_attribute. format_type()
// spells types the way sqlclient.ColumnType canonicalizes configuration.
func readTableAttributesQuery(spec tableSpec) sqlclient.Query {
	return sqlclient.Select("a.attnum AS position", "a.attname AS column_name", "format_type(a.atttypid, a.atttypmod) AS data_type", "a.attnotnull AS not_null").
		From("pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace").
		Where("n.nspname = :schema", sqlclient.Bind("schema", spec.schema)).
		Where("c.relname = :name", sqlclient.Bind("name", spec.name)).
		Where("a.attnum > 0").
		Where("NOT a.attisdropped").
		OrderBy("a.attnum")
}

// readTableColumnsQuery reads defaults, encodings, and key membership from SVV_REDSHIFT_COLUMNS, which, unlike
// PG_TABLE_DEF, does not depend on search_path. https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_REDSHIFT_COLUMNS.html
func readTableColumnsQuery(database string, spec tableSpec) sqlclient.Query {
	return sqlclient.Select("column_name", "column_default", "encoding", "distkey", "sortkey").
		From("svv_redshift_columns").
		Where("database_name = :database", sqlclient.Bind("database", database)).
		Where("schema_name = :schema", sqlclient.Bind("schema", spec.schema)).
		Where("table_name = :name", sqlclient.Bind("name", spec.name)).
		OrderBy("ordinal_position")
}

// readTableConstraintsQuery reads primary key, unique, and foreign key constraints with their catalog names, which
// DROP CONSTRAINT needs, and the referenced table of foreign keys.
func readTableConstraintsQuery(spec tableSpec) sqlclient.Query {
	return sqlclient.Select("con.conname AS constraint_name", "con.contype AS constraint_type", "pg_get_constraintdef(con.oid) AS definition", "rn.nspname AS referenced_schema", "rc.relname AS referenced_table").
		From("pg_constraint con JOIN pg_class c ON c.oid = con.conrelid JOIN pg_namespace n ON n.oid = c.relnamespace "+
			"LEFT JOIN pg_class rc ON rc.oid = con.confrelid LEFT JOIN pg_namespace rn ON rn.oid = rc.relnamespace").
		Where("n.nspname = :schema", sqlclient.Bind("schema", spec.schema)).
		Where("c.relname = :name", sqlclient.Bind("name", spec.name)).
		Where("con.contype IN ('p', 'u', 'f')").
		OrderBy("con.conname")
}

// readTableSortKeyQuery asks SVV_TABLE_INFO whether a sort key is still automatic (AUTO(SORTKEY(column))). The view
// requires superuser or a SELECT grant, so read consults it only when a table configured with AUTO reports sort key
// columns; it lists only tables with rows, so a missing row keeps AUTO.
// https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_TABLE_INFO.html
func readTableSortKeyQuery(spec tableSpec) sqlclient.Query {
	return sqlclient.Select("sortkey1").From("svv_table_info").
		Where(`"schema" = :schema`, sqlclient.Bind("schema", spec.schema)).
		Where(`"table" = :name`, sqlclient.Bind("name", spec.name))
}
