package provider

import (
	"context"
	"fmt"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netcheck-de/terraform-provider-redshift/internal/sqlclient"
)

// tableCastPattern matches a type cast after whitespace removal, such as ::charactervarying(256), which the
// catalog adds to defaults.
var tableCastPattern = regexp.MustCompile(`::[a-z_"]+(\(\d+(,\d+)?\))?`)

// tableIdentityPattern matches the column default Redshift stores for IDENTITY ("identity") and GENERATED BY
// DEFAULT AS IDENTITY (default_identity) columns: the table OID, the column index, and 'seed,step'.
var tableIdentityPattern = regexp.MustCompile(`^"?(identity|default_identity)"?\(\s*\d+\s*,\s*\d+\s*,\s*'\s*(-?\d+)\s*,\s*(-?\d+)\s*'(::text)?\s*\)$`)

// tableCatalogColumn is one column as the catalog reports it.
type tableCatalogColumn struct {
	// name is the column name.
	name string
	// dataType is the canonical spelling of format_type(), as sqlclient.CatalogType reports it.
	dataType string
	// notNull is pg_attribute.attnotnull.
	notNull bool
	// defaultText is the stored default expression, empty without one or for identity columns.
	defaultText string
	// identity is parsed from the stored default of identity columns.
	identity *tableIdentitySpec
	// encoding is the keyword spelling of the compression encoding.
	encoding string
	// distKey marks the distribution key column.
	distKey bool
	// sortKey is the signed sort key position; negative positions mark an interleaved key.
	sortKey int
}

// tableCatalogConstraint is one primary key, unique, or foreign key constraint.
type tableCatalogConstraint struct {
	// name is the constraint name DROP CONSTRAINT needs.
	name string
	// kind is p, u, or f.
	kind string
	// columns are the constrained columns.
	columns []string
	// refSchema, refTable, and refColumns describe the referenced table of a foreign key.
	refSchema, refTable string
	refColumns          []string
}

// tableCatalog is everything read reports about one table.
type tableCatalog struct {
	// owner is the owning user.
	owner string
	// distStyle is the declared AUTO, EVEN, KEY, or ALL.
	distStyle string
	// effectiveDistStyle is the EVEN, KEY, or ALL distribution Redshift applies, or "" when PG_CLASS_INFO does not
	// report it.
	effectiveDistStyle string
	// columns are in attnum order.
	columns []tableCatalogColumn
	// constraints are in name order.
	constraints []tableCatalogConstraint
	// sortKeyListed reports that SVV_TABLE_INFO lists the table, which it does only for tables with rows that the
	// SQL identity may see.
	sortKeyListed bool
	// sortKey1 is SVV_TABLE_INFO.sortkey1 of a listed table.
	sortKey1 string
}

// tableCatalogBool reads a boolean as the Data API and pgx transports spell it.
func tableCatalogBool(value string) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "true", "t", "1", "yes":
		return true
	}
	return false
}

// tableDistStyleNames maps pg_class.reldiststyle to the configured style; 9 covers every AUTO(...) form.
var tableDistStyleNames = map[string]string{"0": "EVEN", "1": "KEY", "8": "ALL", "9": "AUTO"}

// tableEffectiveDistStyleNames maps PG_CLASS_INFO.releffectivediststyle to the style Redshift applies; 10, 11, and
// 12 are AUTO(ALL), AUTO(EVEN), and AUTO(KEY).
var tableEffectiveDistStyleNames = map[string]string{"0": "EVEN", "1": "KEY", "8": "ALL", "10": "ALL", "11": "EVEN", "12": "KEY"}

// tableEncodingName maps the catalog spelling to the CREATE TABLE keyword; the catalog reports RAW as none.
func tableEncodingName(value string) string {
	encoding := strings.ToUpper(strings.TrimSpace(value))
	if encoding == "NONE" || encoding == "" {
		return "RAW"
	}
	return encoding
}

// tableParseIdentity recognizes the stored default of an identity column.
func tableParseIdentity(defaultText string) *tableIdentitySpec {
	match := tableIdentityPattern.FindStringSubmatch(strings.TrimSpace(defaultText))
	if match == nil {
		return nil
	}
	seed, seedErr := strconv.ParseInt(match[2], 10, 64)
	step, stepErr := strconv.ParseInt(match[3], 10, 64)
	if seedErr != nil || stepErr != nil {
		return nil
	}
	return &tableIdentitySpec{seed: seed, step: step, generatedByDefault: match[1] == "default_identity"}
}

// tableCatalogFrom combines the table, pg_attribute, SVV_REDSHIFT_COLUMNS, pg_constraint, and SVV_TABLE_INFO rows.
// It fails on rows that disagree, because a partial definition would plan a destructive replacement.
func tableCatalogFrom(table sqlclient.Row, attributes, columns, constraints, sortKeys []sqlclient.Row) (tableCatalog, error) {
	catalog := tableCatalog{owner: strings.TrimSpace(table["owner"])}
	if catalog.owner == "" {
		return catalog, fmt.Errorf("the catalog reports no owner")
	}
	style, ok := tableDistStyleNames[strings.TrimSpace(table["diststyle"])]
	if !ok {
		return catalog, fmt.Errorf("unsupported distribution style %q", table["diststyle"])
	}
	catalog.distStyle = style
	catalog.effectiveDistStyle = tableEffectiveDistStyleNames[strings.TrimSpace(table["effective_diststyle"])]
	if len(sortKeys) > 0 {
		catalog.sortKeyListed, catalog.sortKey1 = true, strings.TrimSpace(sortKeys[0]["sortkey1"])
	}
	details := map[string]sqlclient.Row{}
	for _, row := range columns {
		details[row["column_name"]] = row
	}
	if len(attributes) == 0 || len(details) != len(attributes) {
		return catalog, fmt.Errorf("pg_attribute and svv_redshift_columns report different columns")
	}
	for _, row := range attributes {
		detail, ok := details[row["column_name"]]
		if !ok {
			return catalog, fmt.Errorf("svv_redshift_columns does not report column %q", row["column_name"])
		}
		sortKey, err := strconv.Atoi(strings.TrimSpace(detail["sortkey"]))
		if err != nil {
			return catalog, fmt.Errorf("column %q has an invalid sort key position %q", row["column_name"], detail["sortkey"])
		}
		column := tableCatalogColumn{
			name: row["column_name"], dataType: sqlclient.CatalogType(row["data_type"]), notNull: tableCatalogBool(row["not_null"]),
			defaultText: strings.TrimSpace(detail["column_default"]), encoding: tableEncodingName(detail["encoding"]),
			distKey: tableCatalogBool(detail["distkey"]), sortKey: sortKey,
		}
		if column.identity = tableParseIdentity(column.defaultText); column.identity != nil {
			column.defaultText = ""
		}
		catalog.columns = append(catalog.columns, column)
	}
	for _, row := range constraints {
		constraint := tableCatalogConstraint{name: row["constraint_name"], kind: strings.TrimSpace(row["constraint_type"]), refSchema: row["referenced_schema"], refTable: row["referenced_table"]}
		var err error
		constraint.columns, constraint.refColumns, err = tableParseConstraintDefinition(row["definition"], constraint.kind == "f")
		if err != nil {
			return catalog, fmt.Errorf("constraint %q: %w", constraint.name, err)
		}
		if constraint.kind == "f" && (constraint.refSchema == "" || constraint.refTable == "") {
			return catalog, fmt.Errorf("constraint %q references a table the catalog does not report", constraint.name)
		}
		catalog.constraints = append(catalog.constraints, constraint)
	}
	return catalog, nil
}

// tableIdentifierList parses a parenthesized identifier list starting at text[start] == '(' as
// pg_get_constraintdef prints it: quoted identifiers double embedded quotes, others are printed as stored.
func tableIdentifierList(text string, start int) ([]string, int, error) {
	if start >= len(text) || text[start] != '(' {
		return nil, 0, fmt.Errorf("expected a column list in %q", text)
	}
	var names []string
	var current strings.Builder
	quoted, pending := false, false
	for i := start + 1; i < len(text); i++ {
		char := text[i]
		switch {
		case quoted && char == '"' && i+1 < len(text) && text[i+1] == '"':
			current.WriteByte('"')
			i++
		case char == '"':
			quoted, pending = !quoted, true
		case quoted:
			current.WriteByte(char)
		case char == ',' || char == ')':
			if !pending && current.Len() == 0 {
				return nil, 0, fmt.Errorf("empty column name in %q", text)
			}
			names = append(names, current.String())
			current.Reset()
			pending = false
			if char == ')' {
				return names, i + 1, nil
			}
		case char == ' ':
		default:
			current.WriteByte(char)
			pending = true
		}
	}
	return nil, 0, fmt.Errorf("unterminated column list in %q", text)
}

// tableParseConstraintDefinition extracts the constrained and, for foreign keys, referenced columns from
// pg_get_constraintdef output such as PRIMARY KEY (id) or FOREIGN KEY (a) REFERENCES s.t(b). The referenced table
// comes from pg_constraint.confrelid instead, because the printed name omits schemas on the search path.
func tableParseConstraintDefinition(definition string, foreign bool) ([]string, []string, error) {
	open := strings.IndexByte(definition, '(')
	if open < 0 {
		return nil, nil, fmt.Errorf("unexpected definition %q", definition)
	}
	columns, end, err := tableIdentifierList(definition, open)
	if err != nil || !foreign {
		return columns, nil, err
	}
	rest := definition[end:]
	marker := strings.Index(rest, "REFERENCES ")
	if marker < 0 {
		return nil, nil, fmt.Errorf("foreign key definition %q has no REFERENCES clause", definition)
	}
	quoted := false
	for i := end + marker + len("REFERENCES "); i < len(definition); i++ {
		switch char := definition[i]; {
		case char == '"':
			quoted = !quoted
		case char == '(' && !quoted:
			refColumns, _, err := tableIdentifierList(definition, i)
			return columns, refColumns, err
		}
	}
	return nil, nil, fmt.Errorf("foreign key definition %q has no referenced columns", definition)
}

// tableStringListValue builds a list of strings.
func tableStringListValue(values []string) types.List {
	elements := make([]attr.Value, len(values))
	for i, value := range values {
		elements[i] = types.StringValue(value)
	}
	return types.ListValueMust(types.StringType, elements)
}

// tableOptionalString returns null for an empty string.
func tableOptionalString(value string) types.String {
	if value == "" {
		return types.StringNull()
	}
	return types.StringValue(value)
}

// tableEffectiveDistributionValue builds an effective_distribution value; empty strings are null.
func tableEffectiveDistributionValue(style, key string, auto bool) types.Object {
	return types.ObjectValueMust(tableEffectiveDistributionAttributeTypes, map[string]attr.Value{
		"style": tableOptionalString(style), "key": tableOptionalString(key), "auto": types.BoolValue(auto),
	})
}

// tableEffectiveSortKeyValue builds an effective_sort_key value; a table without a sort key has no columns.
func tableEffectiveSortKeyValue(style string, columns []string, auto bool) types.Object {
	return types.ObjectValueMust(tableEffectiveSortKeyAttributeTypes, map[string]attr.Value{
		"style": tableOptionalString(style), "columns": tableStringListValue(columns), "auto": types.BoolValue(auto),
	})
}

// tableEffectiveSortColumns returns the columns of a known effective_sort_key value.
func tableEffectiveSortColumns(value types.Object) []string {
	if value.IsNull() || value.IsUnknown() {
		return nil
	}
	list, ok := value.Attributes()["columns"].(types.List)
	if !ok {
		return nil
	}
	columns, err := tableStringList(list, "effective_sort_key.columns")
	if err != nil {
		return nil
	}
	return columns
}

// tableKeepEmpty reports an absent catalog set as the prior value when that was null or empty, so both spellings of
// no constraints stay as they were.
func tableKeepEmpty(prior, null types.Set) types.Set {
	if !prior.IsNull() && !prior.IsUnknown() && len(prior.Elements()) == 0 {
		return prior
	}
	return null
}

// tableColumnOrder orders the catalog's column names by the prior state's or plan's names, with columns they do not
// know appended in physical order. Redshift appends every added column, so physical order would show a column
// declared in the middle as moved and fail Terraform's check that the applied list keeps the planned order.
func tableColumnOrder(prior, physical []string) []string {
	present := map[string]bool{}
	for _, name := range physical {
		present[name] = true
	}
	ordered := make([]string, 0, len(physical))
	seen := map[string]bool{}
	for _, name := range append(slices.Clone(prior), physical...) {
		if present[name] && !seen[name] {
			ordered = append(ordered, name)
			seen[name] = true
		}
	}
	return ordered
}

// tablePriorSortStyle returns the sort key style the prior state declares: AUTO for an omitted block, and "" when
// nothing was configured, as after import or in a lookup.
func tablePriorSortStyle(prior tableModel) string {
	if prior.Column.IsNull() || prior.Column.IsUnknown() {
		return ""
	}
	style, _, known := tableSortKeyBlock(prior.SortKey)
	if !known {
		return ""
	}
	return style
}

// tableDeclaredSortStyle decides the declared sort key style. Sort key positions cannot tell a key Redshift chose
// under AUTO from an explicit one, nor AUTO without a chosen key from NONE; SVV_TABLE_INFO.sortkey1 can, but only
// for tables it lists. Without a row, the prior style is kept where it matches the positions: AUTO for a compound
// key, and AUTO or NONE without one.
func tableDeclaredSortStyle(catalog tableCatalog, columns []string, interleaved bool, prior string) string {
	auto := strings.HasPrefix(strings.ToUpper(catalog.sortKey1), "AUTO(")
	switch {
	case interleaved:
		return "INTERLEAVED"
	case catalog.sortKeyListed && auto:
		return "AUTO"
	case len(columns) == 0 && (catalog.sortKeyListed || prior == "NONE"):
		return "NONE"
	case len(columns) == 0:
		return "AUTO"
	case !catalog.sortKeyListed && prior == "AUTO":
		return "AUTO"
	}
	return "COMPOUND"
}

// tableReconcile turns the catalog into Terraform values. Configured spellings are kept where the catalog spells
// the same thing differently: a type alias with the same canonical form, any default while the catalog still has
// one, and an empty set of constraints. Columns keep the prior order, matched by name. The distribution and
// sort_key blocks are reported when the prior state had them or the catalog declares something other than AUTO, so
// an omitted block stays omitted until the layout drifts. backup is not observable in a catalog every deployment
// exposes, so the prior value stays. It also returns the constraint names keyed for DROP CONSTRAINT.
func tableReconcile(prior tableModel, catalog tableCatalog) (tableModel, map[string]string, error) {
	ctx := context.Background()
	observed := prior
	observed.Owner = types.StringValue(catalog.owner)
	priorColumns := map[string]tableColumnModel{}
	var priorOrder []string
	if !prior.Column.IsNull() && !prior.Column.IsUnknown() {
		var columns []tableColumnModel
		if diagnostics := prior.Column.ElementsAs(ctx, &columns, false); !diagnostics.HasError() {
			for _, column := range columns {
				priorColumns[column.Name.ValueString()] = column
				priorOrder = append(priorOrder, column.Name.ValueString())
			}
		}
	}
	models := map[string]tableColumnModel{}
	var physical, sortKey []string
	interleaved := false
	distKey := ""
	type position struct {
		order int
		name  string
	}
	var sortPositions []position
	for _, column := range catalog.columns {
		before, known := priorColumns[column.name]
		model := tableColumnModel{
			Name: types.StringValue(column.name), Type: types.StringValue(column.dataType),
			Encoding: types.StringValue(column.encoding), Nullable: types.BoolValue(!column.notNull),
			Default: types.StringNull(), Identity: types.ObjectNull(tableIdentityAttributeTypes),
		}
		if known && !before.Type.IsNull() && !before.Type.IsUnknown() {
			if canonical, err := sqlclient.ColumnType(before.Type.ValueString()); err == nil && string(canonical) == column.dataType {
				model.Type = before.Type
			}
		}
		if column.defaultText != "" {
			model.Default = types.StringValue(column.defaultText)
			if known && !before.Default.IsNull() && !before.Default.IsUnknown() {
				model.Default = before.Default
			}
		}
		if identity := column.identity; identity != nil {
			model.Identity = types.ObjectValueMust(tableIdentityAttributeTypes, map[string]attr.Value{
				"seed": types.Int64Value(identity.seed), "step": types.Int64Value(identity.step), "generated_by_default": types.BoolValue(identity.generatedByDefault),
			})
		}
		models[column.name] = model
		physical = append(physical, column.name)
		if column.distKey {
			distKey = column.name
		}
		if column.sortKey != 0 {
			order := column.sortKey
			if order < 0 {
				order, interleaved = -order, true
			}
			sortPositions = append(sortPositions, position{order: order, name: column.name})
		}
	}
	slices.SortFunc(sortPositions, func(a, b position) int { return a.order - b.order })
	for _, entry := range sortPositions {
		sortKey = append(sortKey, entry.name)
	}
	columns := make([]tableColumnModel, 0, len(physical))
	for _, name := range tableColumnOrder(priorOrder, physical) {
		columns = append(columns, models[name])
	}
	list, diagnostics := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: tableColumnAttributeTypes}, columns)
	if diagnostics.HasError() {
		return observed, nil, fmt.Errorf("convert columns: %v", diagnostics)
	}
	observed.Column = list

	declaredKey := ""
	if catalog.distStyle == "KEY" {
		if distKey == "" {
			return observed, nil, fmt.Errorf("the catalog reports DISTSTYLE KEY without a distribution key column")
		}
		declaredKey = distKey
	}
	observed.Distribution = types.ObjectNull(tableDistributionAttributeTypes)
	if !prior.Distribution.IsNull() || catalog.distStyle != "AUTO" {
		observed.Distribution = types.ObjectValueMust(tableDistributionAttributeTypes, map[string]attr.Value{
			"style": types.StringValue(catalog.distStyle), "key": tableOptionalString(declaredKey),
		})
	}
	effectiveStyle := catalog.distStyle
	if effectiveStyle == "AUTO" {
		effectiveStyle = catalog.effectiveDistStyle
		if effectiveStyle == "" && distKey != "" {
			effectiveStyle = "KEY"
		}
	}
	effectiveKey := ""
	if effectiveStyle == "KEY" {
		effectiveKey = distKey
	}
	observed.EffectiveDistribution = tableEffectiveDistributionValue(effectiveStyle, effectiveKey, catalog.distStyle == "AUTO")

	declared := tableDeclaredSortStyle(catalog, sortKey, interleaved, tablePriorSortStyle(prior))
	observed.SortKey = types.ObjectNull(tableSortKeyAttributeTypes)
	if !prior.SortKey.IsNull() || declared != "AUTO" {
		declaredColumns := types.ListNull(types.StringType)
		if declared == "COMPOUND" || declared == "INTERLEAVED" {
			declaredColumns = tableStringListValue(sortKey)
		}
		observed.SortKey = types.ObjectValueMust(tableSortKeyAttributeTypes, map[string]attr.Value{
			"style": types.StringValue(declared), "columns": declaredColumns,
		})
	}
	physicalSort := "NONE"
	switch {
	case interleaved:
		physicalSort = "INTERLEAVED"
	case len(sortKey) > 0:
		physicalSort = "COMPOUND"
	}
	observed.EffectiveSortKey = tableEffectiveSortKeyValue(physicalSort, sortKey, declared == "AUTO")

	names := map[string]string{}
	observed.PrimaryKey = types.ObjectNull(tableKeyAttributeTypes)
	var unique []attr.Value
	var foreignKeys []attr.Value
	keyType := types.ObjectType{AttrTypes: tableKeyAttributeTypes}
	foreignKeyType := types.ObjectType{AttrTypes: tableForeignKeyAttributeTypes}
	for _, constraint := range catalog.constraints {
		columns := map[string]attr.Value{"columns": tableStringListValue(constraint.columns)}
		switch constraint.kind {
		case "p":
			observed.PrimaryKey = types.ObjectValueMust(tableKeyAttributeTypes, columns)
			names[tablePrimaryKeyKey] = constraint.name
		case "u":
			unique = append(unique, types.ObjectValueMust(tableKeyAttributeTypes, columns))
			names[tableUniqueKey(constraint.columns)] = constraint.name
		case "f":
			foreignKeys = append(foreignKeys, types.ObjectValueMust(tableForeignKeyAttributeTypes, map[string]attr.Value{
				"columns": tableStringListValue(constraint.columns),
				"references": types.ObjectValueMust(tableReferencesAttributeTypes, map[string]attr.Value{
					"schema": types.StringValue(constraint.refSchema), "table": types.StringValue(constraint.refTable), "columns": tableStringListValue(constraint.refColumns),
				}),
			}))
			names[tableForeignKeyKey(tableForeignKeySpec{columns: constraint.columns, refSchema: constraint.refSchema, refTable: constraint.refTable, refColumns: constraint.refColumns})] = constraint.name
		}
	}
	observed.Unique = tableKeepEmpty(prior.Unique, types.SetNull(keyType))
	if len(unique) > 0 {
		observed.Unique = types.SetValueMust(keyType, unique)
	}
	observed.ForeignKey = tableKeepEmpty(prior.ForeignKey, types.SetNull(foreignKeyType))
	if len(foreignKeys) > 0 {
		observed.ForeignKey = types.SetValueMust(foreignKeyType, foreignKeys)
	}
	if observed.Backup.IsUnknown() {
		observed.Backup = types.StringNull()
	}
	return observed, names, nil
}

// tableConverged checks that the catalog holds what the plan requested, matching columns by name; values the plan
// leaves to Redshift, such as unknown encodings, are not compared.
func tableConverged(plan, observed tableSpec) error {
	if len(plan.columns) != len(observed.columns) {
		return fmt.Errorf("the table has %d columns instead of %d", len(observed.columns), len(plan.columns))
	}
	for _, want := range plan.columns {
		got, found := observed.column(want.name)
		switch {
		case !found:
			return fmt.Errorf("column %q is missing", want.name)
		case got.dataType != want.dataType:
			return fmt.Errorf("column %q has type %s instead of %s", want.name, got.dataType, want.dataType)
		case want.encoding != "" && got.encoding != want.encoding:
			return fmt.Errorf("column %q has encoding %s instead of %s", want.name, got.encoding, want.encoding)
		case want.nullable != nil && got.nullable != nil && *got.nullable != *want.nullable:
			return fmt.Errorf("column %q has the wrong nullability", want.name)
		case (want.defaultSQL == "") != (got.defaultSQL == ""):
			return fmt.Errorf("column %q has the wrong default", want.name)
		case !tableIdentityEqual(want.identity, got.identity):
			return fmt.Errorf("column %q has the wrong identity", want.name)
		}
	}
	switch {
	case !slices.Equal(plan.primaryKey, observed.primaryKey):
		return fmt.Errorf("the primary key is %v instead of %v", observed.primaryKey, plan.primaryKey)
	case !slices.EqualFunc(plan.unique, observed.unique, slices.Equal):
		return fmt.Errorf("the unique constraints are %v instead of %v", observed.unique, plan.unique)
	case !slices.EqualFunc(plan.foreignKeys, observed.foreignKeys, func(a, b tableForeignKeySpec) bool { return tableForeignKeyKey(a) == tableForeignKeyKey(b) }):
		return fmt.Errorf("the foreign keys differ from the configuration")
	case plan.distStyle != observed.distStyle || plan.distKey != observed.distKey:
		return fmt.Errorf("the distribution is %s %s instead of %s %s", observed.distStyle, observed.distKey, plan.distStyle, plan.distKey)
	case plan.sortStyle != observed.sortStyle || !slices.Equal(plan.sortKey, observed.sortKey):
		return fmt.Errorf("the sort key is %s %v instead of %s %v", observed.sortStyle, observed.sortKey, plan.sortStyle, plan.sortKey)
	case plan.owner != "" && plan.owner != observed.owner:
		return fmt.Errorf("the owner is %q instead of %q", observed.owner, plan.owner)
	}
	return nil
}
